const {test}=require('node:test'),assert=require('node:assert/strict'),L=require('./lesson-engine');
const uid=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
class Store{
 constructor(){this.tables={demo_access:[{email:'owner@example.edu',role:'owner',active:true},{email:'prof@example.edu',role:'professor',active:true},{email:'other@example.edu',role:'professor',active:true}],demo_profiles:[],demo_classes:[],demo_invitations:[],demo_assignments:[],demo_runs:[],demo_attempts:[]};}
 async list(t,f){return structuredClone(this.tables[t].filter(x=>Object.entries(f).every(([k,v])=>x[k]===v)));}
 async one(t,f){return (await this.list(t,f))[0]||null;}
 async insert(t,x){this.tables[t].push(structuredClone(x));return structuredClone(x);}
 async upsert(t,x){const keys=t==='demo_access'?['email']:['class_id','email'];const old=this.tables[t].find(r=>keys.every(k=>r[k]===x[k]));old?Object.assign(old,structuredClone(x)):this.tables[t].push(structuredClone(x));return x;}
 async update(t,f,x){for(const r of this.tables[t])if(Object.entries(f).every(([k,v])=>r[k]===v))Object.assign(r,structuredClone(x));}
 async remove(t,f){this.tables[t]=this.tables[t].filter(r=>!Object.entries(f).every(([k,v])=>r[k]===v));}
 async commit(student,assignment,revision,state,action,p){const row=this.tables.demo_runs.find(r=>r.student_id===student&&r.assignment_id===assignment);if((row?.revision||0)!==revision)throw Error('CONFLICT');const v={student_id:student,assignment_id:assignment,revision:revision+1,state:structuredClone(state)};row?Object.assign(row,v):this.tables.demo_runs.push(v);this.tables.demo_attempts.push({student_id:student,assignment_id:assignment,revision:v.revision,action,created_at:new Date().toISOString(),submitted:structuredClone(p)});return {state:structuredClone(state),revision:v.revision};}
}
const owner={id:uid(1),email:'owner@example.edu'},prof={id:uid(2),email:'prof@example.edu'},other={id:uid(3),email:'other@example.edu'},student={id:uid(4),email:'student@example.edu'},outsider={id:uid(5),email:'outsider@example.edu'};
async function fixture(topic='prepaid'){
 const {handleAction}=await import('./supabase/functions/classroom/service.mjs'),store=new Store(),call=(u,a,p)=>handleAction(store,L,u,a,p);
 const c=await call(prof,'create-class',{name:'Intro Financial'});await call(prof,'invite',{classId:c.id,email:student.email});
 await call(student,'business',{business:{name:'Tommy’s Coffee',type:'Coffee shop',color:'sage'}});
 const a=await call(prof,'publish',{classId:c.id,assignment:{version:1,id:'draft',title:'Lesson',topic,course:'Intro',instructions:'Practice',year:2026,month:9,support:'guided',notes:''}});
 return {store,call,c,a};
}
test('unapproved accounts and user-supplied role claims cannot get access',async()=>{const {call}=await fixture();await assert.rejects(()=>call({...outsider,user_metadata:{role:'owner'}},'bootstrap'),e=>e.status===403);await assert.rejects(()=>call(student,'authorize',{email:outsider.email,role:'professor',active:true}),e=>e.status===403);});
test('professors cannot inspect or publish in other professors’ classes',async()=>{const {call,c,a}=await fixture();await assert.rejects(()=>call(other,'gradebook',{classId:c.id}),e=>e.status===403);await assert.rejects(()=>call(other,'publish',{classId:c.id,assignment:a.definition}),e=>e.status===403);await assert.rejects(()=>call(other,'attempts',{studentId:student.id,assignmentId:a.id}),e=>e.status===403);});
test('owner approvals and revocations apply on the next request',async()=>{const {call}=await fixture();await call(owner,'authorize',{email:outsider.email,role:'professor',active:true});assert.equal((await call(outsider,'bootstrap')).user.role,'professor');await call(owner,'authorize',{email:outsider.email,role:'professor',active:false});await assert.rejects(()=>call(outsider,'bootstrap'),e=>e.status===403);await assert.rejects(()=>call(owner,'authorize',{email:owner.email,role:'student',active:false}));});
test('class invitations scope student assignments and removing access prevents submissions',async()=>{const {call,c,a}=await fixture();const boot=await call(student,'bootstrap');assert.equal(boot.assignments.length,1);await call(prof,'remove-student',{classId:c.id,email:student.email});assert.equal((await call(student,'bootstrap')).assignments.length,0);await assert.rejects(()=>call(student,'start',{assignmentId:a.id,revision:0,choice:{location:0,months:3}}),e=>e.status===403);});
test('server computes immutable first grades, ignores forged scores, and rejects stale tabs',async()=>{const {call,a,store}=await fixture();const submit=(action,p)=>call(student,action,{assignmentId:a.id,...p});let v=await submit('start',{revision:0,choice:{location:0,months:3},first:{},serverGrade:{journal:80}});assert.equal(v.state.serverGrade.journal,0);const e=v.state.scenario.events[0];const wrong=[{account:'Rent Expense',debit:450},{account:'Cash',credit:450}];v=await submit('entry',{revision:1,record:e.id,date:'2026-09-02',rows:wrong,first:{correct:true}});assert.equal(v.state.first.payment.correct,false);const correct=[{account:e.debit,debit:e.amount},{account:e.credit,credit:e.amount}];await assert.rejects(()=>submit('entry',{revision:1,record:e.id,date:e.date,rows:correct}),e=>e.status===409);v=await submit('entry',{revision:2,record:e.id,date:e.date,rows:correct});assert.equal(v.state.first.payment.correct,false);assert.equal(L.assess(v.state.entries.payment.rows,e.date,e).correct,true);assert.equal(store.tables.demo_attempts.length,3);assert.equal(store.tables.demo_attempts[1].submitted.rows[0].account,'Rent Expense');});
test('completion requires correct entries and preserves original prediction and financial attempts',async()=>{const {call,a}=await fixture('equipment');let rev=0;const submit=async(action,p)=>{const v=await call(student,action,{assignmentId:a.id,revision:rev,...p});rev=v.revision;return v.state;};let r=await submit('start',{choice:{level:2,life:1}});await assert.rejects(()=>submit('effects',{values:{expense:30,remaining:1770,cash:6200}}));r=await submit('advance',{});for(const e of r.scenario.events)r=await submit('entry',{record:e.id,date:e.date,rows:[{account:e.debit,debit:e.amount},{account:e.credit,credit:e.amount}]});r=await submit('prediction',{answer:0});await assert.rejects(()=>submit('prediction',{answer:2}));r=await submit('effects',{values:{expense:0,remaining:1800,cash:6200}});assert.equal(r.completed,false);r=await submit('effects',{values:{expense:30,remaining:1770,cash:6200}});assert.equal(r.completed,true);assert.deepEqual(r.serverGrade,{journal:80,effects:5,prediction:0});});
test('malformed journal rows and invalid business choices cannot be recorded',async()=>{const {call,a}=await fixture();await assert.rejects(()=>call(student,'start',{assignmentId:a.id,revision:0,choice:{location:5,months:0}}));await call(student,'start',{assignmentId:a.id,revision:0,choice:{location:0,months:3}});await assert.rejects(()=>call(student,'entry',{assignmentId:a.id,revision:1,record:'payment',date:'2026-09-01',rows:[{account:'Cash',debit:100},{account:'Rent Expense',credit:90}]}));});
test('professor cannot restore a student disabled by the owner',async()=>{const {call,c}=await fixture();await call(owner,'authorize',{email:student.email,role:'student',active:false});await assert.rejects(()=>call(prof,'invite',{classId:c.id,email:student.email}),/disabled/);});
test('generated cloud episodes preserve design, enforce stages, and grade the complete journal on the server',async()=>{const {call,c}=await fixture();const business={name:'Tommy’s Bakery',type:'Bakery',color:'plum',style:'Garden storefront',district:'Campus village',logo:'◇',specialty:'Custom cakes',tagline:'Baked for you'};assert.equal((await call(student,'business',{business})).business.specialty,'Custom cakes');const definition=L.generateAssignment('Supplies physical counts, accrued wages and customer deposits are unearned revenue.',{id:'generated'}),a=await call(prof,'publish',{classId:c.id,assignment:definition});let revision=0;const submit=async(action,p={})=>{const v=await call(student,action,{assignmentId:a.id,revision,...p});revision=v.revision;return v.state;};let r=await submit('start',{choice:L.defaultEpisodeChoice(definition)});assert.equal(r.business.style,'Garden storefront');const locked=r.scenario.events.find(e=>e.stage===2);await assert.rejects(()=>submit('entry',{record:locked.id,date:locked.date,rows:[{account:locked.debit,debit:locked.amount},{account:locked.credit,credit:locked.amount}]}),/not available/);r=await submit('advance');assert.equal(r.stage,1);assert.equal(r.advanced,false);r=await submit('advance');assert.equal(r.stage,2);assert.equal(r.advanced,true);for(const e of r.scenario.events)r=await submit('entry',{record:e.id,date:e.date,rows:[{account:e.debit,debit:e.amount},{account:e.credit,credit:e.amount}]});r=await submit('prediction',{answer:r.scenario.prediction.correct});r=await submit('effects',{values:Object.fromEntries(r.scenario.effects.map(e=>[e.key,e.value]))});assert.equal(r.completed,true);assert.deepEqual(r.serverGrade,{journal:80,prediction:5,effects:15});await assert.rejects(()=>call(student,'business',{business:{...business,type:'Coffee shop',specialty:'Coffee & pastries'}}),/cannot change/);});
test('original generated assignments are authorized and graded with their own chart of accounts',async()=>{const {call,c,store}=await fixture(),{draft}=require('./test-fixtures/generated-assignment.cjs');store.generate=async input=>{assert.equal(input.actor,prof.id);return draft();};await assert.rejects(()=>call(student,'generate',{notes:draft().notes}),e=>e.status===403);const definition=await call(prof,'generate',{notes:draft().notes});const a=await call(prof,'publish',{classId:c.id,assignment:definition});let revision=0;const submit=async(action,p={})=>{const v=await call(student,action,{assignmentId:a.id,revision,...p});revision=v.revision;return v.state;};let r=await submit('start',{choice:{plan:2}});await submit('advance');r=await submit('advance');for(const e of a.definition.blueprint.paths[2].events)r=await submit('entry',{record:e.id,date:e.date,rows:e.lines});await submit('prediction',{answer:r.scenario.prediction.correct});const expected=L.expected(a.definition,{plan:2});r=await submit('effects',{values:Object.fromEntries(expected.effects.map(e=>[e.key,e.value]))});assert.equal(r.completed,true);assert.equal(r.serverGrade.journal,80);assert.ok(r.scenario.events.every(e=>!e.lines));assert.ok(r.scenario.effects.every(e=>!Object.hasOwn(e,'value')));const boot=await call(student,'bootstrap');assert.ok(boot.assignments.find(x=>x.id===a.id).definition.blueprint.paths.every(p=>p.events.every(e=>!e.lines)));});
