const {test}=require('node:test');const assert=require('node:assert/strict');const {validate,correct}=require('./engine');
const event={amount:200,debit:'Supplies',credit:'Cash'};
test('balanced wrong accounts pass posting but fail audit',()=>{const rows=[{account:'Rent Expense',debit:200,credit:0},{account:'Cash',debit:0,credit:200}];assert.equal(validate(rows,200),null);assert.equal(correct(rows,event),false);});
test('correct journal passes audit',()=>assert.equal(correct([{account:'Supplies',debit:200,credit:0},{account:'Cash',debit:0,credit:200}],event),true));
test('reject imbalance, negative and dual-sided lines',()=>{assert.ok(validate([{account:'Cash',debit:100,credit:0}],100));assert.ok(validate([{account:'Cash',debit:-1,credit:0}],1));assert.ok(validate([{account:'Cash',debit:1,credit:1}],1));});
test('split lines aggregate and cents remain accurate',()=>{const rows=[{account:'Supplies',debit:100.25,credit:0},{account:'Supplies',debit:99.75,credit:0},{account:'Cash',debit:0,credit:200}];assert.equal(validate(rows,200),null);assert.equal(correct(rows,event),true);});
const E=require('./engine');
function entry(id,debit,credit,amount){return {id,event:{debit,credit,amount},rows:[{account:debit,debit:amount,credit:0},{account:credit,debit:0,credit:amount}]};}
test('statements distinguish revenue, customer balances and cash flow',()=>{const ledger=[entry(1,'Cash','Owner Capital',5000),entry(2,'Supplies','Cash',200),entry(3,'Accounts Receivable','Sales Revenue',400),entry(4,'Supplies Expense','Supplies',100),entry(5,'Equipment','Cash',800)];const f=E.financials(ledger);assert.equal(f.profit,300);assert.equal(f.cash,4000);assert.equal(f.receivables,400);assert.equal(f.operating,-200);assert.equal(f.investing,-800);assert.equal(f.financing,5000);assert.equal(f.assets,f.liabilities+f.capital+f.retained);});
test('audit correction replaces original without double counting',()=>{const wrong=entry(1,'Rent Expense','Cash',200),fix=entry(undefined,'Supplies','Cash',200);fix.event.correction=1;const b=E.balances([wrong,fix]);assert.equal(b['Rent Expense'],0);assert.equal(b.Supplies,200);assert.equal(b.Cash,-200);});
test('second period excludes prior revenue and financing',()=>{const first=[entry(1,'Cash','Owner Capital',5000),entry(2,'Cash','Sales Revenue',400)];const second=[...first,entry(3,'Cash','Accounts Receivable',100),entry(4,'Cash','Sales Revenue',200)];const f=E.financials(second,{ledger:first,effectiveCount:2});assert.equal(f.revenue,200);assert.equal(f.financing,0);assert.equal(f.operating,300);assert.equal(f.cash,5700);});
test('prepaid rent stays an asset until used and depreciation reduces net assets',()=>{const l=[entry(1,'Cash','Owner Capital',5000),entry(2,'Prepaid Rent','Cash',900),entry(3,'Rent Expense','Prepaid Rent',300),entry(4,'Equipment','Cash',1200),entry(5,'Depreciation Expense','Accumulated Depreciation',240)];const f=E.financials(l);assert.equal(f.prepaid,600);assert.equal(f.equipment,960);assert.equal(f.profit,-540);assert.equal(f.assets,f.capital+f.retained);});
test('compound managerial variance and annual closing entries validate',()=>{const rows=[{account:'Work in Process',debit:600,credit:0},{account:'Materials Price Variance',debit:100,credit:0},{account:'Raw Materials',debit:0,credit:700}];assert.equal(E.validate(rows,700),null);assert.equal(E.correct(rows,{expectedRows:rows,amount:700}),true);assert.equal(E.correct(rows,{expectedRows:[{account:'Work in Process',debit:700,credit:0},{account:'Raw Materials',debit:0,credit:700}]}),false);});
test('investor funding increases equity and financing cash flow, not profit',()=>{const f=E.financials([entry(1,'Cash','Owner Capital',5000),entry(2,'Cash','Investor Capital',1500)]);assert.equal(f.cash,6500);assert.equal(f.capital,6500);assert.equal(f.financing,6500);assert.equal(f.profit,0);});
test('introductory accruals and customer advances are liabilities until settled or earned',()=>{const l=[entry(1,'Cash','Owner Capital',5000),entry(2,'Supplies','Accounts Payable',120),entry(3,'Cash','Unearned Revenue',180),entry(4,'Wages Expense','Wages Payable',90)];let f=E.financials(l);assert.equal(f.liabilities,390);assert.equal(f.revenue,0);assert.equal(f.profit,-90);l.push(entry(5,'Accounts Payable','Cash',120),entry(6,'Unearned Revenue','Sales Revenue',180));f=E.financials(l);assert.equal(f.liabilities,90);assert.equal(f.revenue,180);assert.equal(f.assets,f.liabilities+f.capital+f.retained);});
