(function(root){
const accounts=['Cash','Accounts Receivable','Supplies','Equipment','Accounts Payable','Owner Capital','Investor Capital','Unearned Revenue','Sales Revenue','Rent Expense','Wages Expense','Supplies Expense','Fine Expense','Advertising Expense','Prepaid Rent','Accumulated Depreciation','Depreciation Expense','Income Summary','Work in Process','Finished Goods','Manufacturing Overhead','Cost of Goods Sold','Raw Materials','Wages Payable','Materials Price Variance'];
function validate(rows,total){let d=0,c=0;for(const r of rows){if(!accounts.includes(r.account))return 'Choose an account on every line.';const debit=Number(r.debit),credit=Number(r.credit);if(!Number.isFinite(debit)||!Number.isFinite(credit)||debit<0||credit<0||((debit>0)===(credit>0)))return 'Each line needs a positive debit OR credit.';d+=Math.round(debit*100);c+=Math.round(credit*100);}if(d!==c)return 'Debits and credits must balance.';if(d!==Math.round(total*100))return 'Check the amount in the business event.';return null;}
function correct(rows,event){const sums={};for(const r of rows){sums[r.account]=(sums[r.account]||0)+Math.round((Number(r.debit)-Number(r.credit))*100);}const expected={};for(const r of (event.expectedRows||[{account:event.debit,debit:event.amount,credit:0},{account:event.credit,debit:0,credit:event.amount}]))expected[r.account]=(expected[r.account]||0)+Math.round((Number(r.debit)-Number(r.credit))*100);return [...new Set([...Object.keys(sums),...Object.keys(expected)])].every(a=>(sums[a]||0)===(expected[a]||0));}
function effective(ledger){const replaced=new Set(ledger.filter(e=>e.event.correction).map(e=>e.event.correction));return ledger.filter(e=>!replaced.has(e.id));}
function balances(ledger){const b=Object.fromEntries(accounts.map(a=>[a,0]));for(const e of effective(ledger))for(const r of e.rows)b[r.account]+=Math.round((Number(r.debit)-Number(r.credit))*100);return Object.fromEntries(Object.entries(b).map(([a,v])=>[a,v/100]));}
function financials(ledger,beginning={}){const b=balances(ledger),old=balances(beginning.ledger||[]);const revenue=-(b['Sales Revenue']-old['Sales Revenue'])||0;const expenses=['Rent Expense','Wages Expense','Supplies Expense','Fine Expense','Advertising Expense','Depreciation Expense'].reduce((t,a)=>t+b[a]-old[a],0);let operating=0,investing=0,financing=0;const period=effective(ledger).slice(beginning.effectiveCount||0);for(const e of period){const cash=e.rows.filter(r=>r.account==='Cash').reduce((t,r)=>t+Number(r.debit)-Number(r.credit),0);if(e.rows.some(r=>['Owner Capital','Investor Capital'].includes(r.account)))financing+=cash;else if(e.rows.some(r=>r.account==='Equipment'))investing+=cash;else operating+=cash;}
return {revenue,expenses,profit:revenue-expenses,cash:b.Cash,receivables:b['Accounts Receivable'],supplies:b.Supplies,equipment:b.Equipment+b['Accumulated Depreciation'],prepaid:b['Prepaid Rent'],assets:b.Cash+b['Accounts Receivable']+b.Supplies+b.Equipment+b['Accumulated Depreciation']+b['Prepaid Rent'],liabilities:-b['Accounts Payable']-b['Wages Payable']-b['Unearned Revenue'],capital:-b['Owner Capital']-b['Investor Capital'],retained:-b['Sales Revenue']-['Rent Expense','Wages Expense','Supplies Expense','Fine Expense','Advertising Expense','Depreciation Expense'].reduce((t,a)=>t+b[a],0),operating,investing,financing,change:operating+investing+financing};}
const api={accounts,validate,correct,effective,balances,financials};if(typeof module!=='undefined')module.exports=api;else root.Engine=api;
})(globalThis);
