const {test}=require('node:test'),assert=require('node:assert/strict'),L=require('./lesson-engine');
const business={name:'Tommy’s Coffee',type:'Coffee shop',color:'sage'};
const notes='Prepaid rent and insurance. Supplies are an asset until used: determine supplies expense using a physical count. Equipment uses straight-line depreciation over its useful life. Customers buy on account and make collections. Customer deposits are unearned revenue until delivery.';
const draft=(extra={})=>L.generateAssignment(notes,{id:'episode-test',report:'statements',...extra});
function postings(s){return Object.fromEntries(s.events.map(e=>[e.id,{date:e.date,rows:[{account:e.debit,debit:e.amount},{account:e.credit,credit:e.amount}]}]));}
test('notes compose only evidenced concepts and expose unsupported scope instead of silently assigning it',()=>{const a=draft();assert.deepEqual(a.concepts,['prepaid','insurance','supplies','receivables','equipment','unearned']);assert.equal(L.checkAssignment(a),true);assert.equal(a.source.length,6);assert.ok(a.source.every(x=>x.evidence));assert.throws(()=>L.generateAssignment('Accounting is interesting and important.',{id:'unknown'}),/No supported/);const scope=L.analyzeNotes('FIFO inventory, bank reconciliation, closing entries and declining-balance depreciation.');assert.ok(scope.unsupported.includes('Inventory valuation and cost of goods sold'));assert.ok(scope.unsupported.includes('Closing entries'));assert.ok(scope.unsupported.includes('Depreciation methods other than straight-line'));});
test('same assignment and business reproduce stable amounts; notes, business and choices affect the scenario',()=>{const a=draft(),c=L.defaultEpisodeChoice(a),s=L.expected(a,c,business);assert.deepEqual(L.expected(a,c,business),s);const chosen=L.expected(a,{...c,prepaid_months:6},business);assert.notEqual(chosen.events.find(e=>e.id==='rent-payment').amount,s.events.find(e=>e.id==='rent-payment').amount);const other=L.expected(a,c,{...business,name:'An entirely different bakery',type:'Bakery'});assert.ok(other.events.find(e=>e.id==='equipment-purchase').detail.lines.some(x=>String(x[1]).includes('oven')));assert.notDeepEqual(other,s);const revised=L.generateAssignment(notes+' Use revised examples.',{id:a.id});assert.notEqual(revised.seed,a.seed);});
test('every generated concept balances and produces correct statement totals across business types and option ranges',()=>{for(const id of Object.keys(L.concepts))for(const type of Object.keys(L.businesses))for(const depth of ['focused','standard','extended'])for(const index of [0,1,2]){const a=L.generateAssignment('Course: '+L.concepts[id].name,{id:'test-'+id,concepts:[id],depth,report:'statements',month:2,year:2028}),c=Object.fromEntries(L.concepts[id].fields.map(([k,,labels,numbers])=>[id+'_'+k,numbers?numbers[index]:index])),s=L.expected(a,c,{name:'Example '+type,type}),entries=postings(s),b=L.balances(s,entries),effects=Object.fromEntries(s.effects.map(e=>[e.key,e.value]));assert.ok(s.events.length>=1);assert.equal(new Set(s.events.map(e=>e.id)).size,s.events.length);assert.ok(s.events.every(e=>e.date>='2028-02-01'&&e.date<='2028-02-29'&&L.validateRows(entries[e.id].rows)===null));assert.ok(Math.abs(Object.values(b).reduce((x,y)=>x+y,0))<.01,id);assert.ok(Math.abs(effects.assets-effects.liabilities-effects.equity)<.01,id);assert.ok(Math.abs(effects.profit-(effects.revenue-effects.expense))<.01,id);assert.equal(effects.cash,b.Cash);}});
test('multi-concept journals and first-attempt grading work for long assignments',()=>{const a=draft({depth:'extended'}),s=L.expected(a,L.defaultEpisodeChoice(a),business),entries=postings(s);assert.ok(s.events.length>=12);const first=Object.fromEntries(s.events.map(e=>[e.id,L.assess(entries[e.id].rows,e.date,e)])),r={scenario:s,first,predictionFirst:s.prediction.correct,effectsFirst:Object.fromEntries(s.effects.map(e=>[e.key,e.value]))};assert.deepEqual(L.grade(r),{journal:80,prediction:5,effects:15});});
test('physical count includes reserve purchases and accrual documents do not disclose adjustment answers',()=>{const a=draft({concepts:['supplies']}),s=L.expected(a,L.defaultEpisodeChoice(a),business),b=L.balances(s,postings(s)),count=s.events.find(e=>e.id==='supplies-count'),remaining=count.detail.lines.find(([k])=>k==='Ending supplies on hand at cost')[1];assert.equal(b.Supplies,remaining);assert.ok(!count.detail.lines.some(([k])=>/expense|debit|credit/i.test(k)));});
test('episodes reveal records by stage and retain compatibility with older two-record lessons',()=>{const a=draft(),s=L.expected(a,L.defaultEpisodeChoice(a),business),r={assignment:a,scenario:s};assert.ok(L.availableEvents(r).every(e=>e.stage===0));r.stage=1;assert.ok(L.availableEvents(r).every(e=>e.stage<=1));r.stage=2;assert.equal(L.availableEvents(r).length,s.events.length);assert.equal(L.availableEvents({assignment:{version:1},scenario:{events:[1,2]},advanced:false}).length,1);});
test('invalid imported plans and forged business choices are rejected',()=>{const a=draft();assert.equal(L.checkAssignment({...a,concepts:['constructor'],topic:'constructor'}),false);assert.equal(L.checkAssignment({...a,concepts:['prepaid','prepaid']}),false);assert.equal(L.checkAssignment({...a,seed:-1}),false);assert.equal(L.checkAssignment({...a,depth:'unlimited'}),false);assert.equal(L.validEpisodeChoice(a,{...L.defaultEpisodeChoice(a),prepaid_months:24}),false);assert.throws(()=>L.expected(a,{}),/valid business/);});
test('business identities validate richer designs and safely default older saved profiles',()=>{const old=L.normalizeBusiness(business);assert.equal(old.specialty,'Coffee & pastries');const design=L.normalizeBusiness({...business,type:'Bakery',specialty:'Custom cakes',style:'Garden storefront',district:'Campus village',color:'plum',logo:'◇',tagline:'Baked for you'});assert.equal(design.tagline,'Baked for you');assert.throws(()=>L.normalizeBusiness({...business,specialty:'Invalid offering'}));assert.throws(()=>L.normalizeBusiness({...business,color:'constructor'}));});
test('note scope distinguishes insurance from rent and credit purchases from credit sales',()=>{assert.deepEqual(L.analyzeNotes('Prepaid insurance coverage is allocated over the policy period.').matches.map(x=>x.id),['insurance']);assert.deepEqual(L.analyzeNotes('Credit purchases of supplies on account and supplier payments.').matches.map(x=>x.id),['supplies','payables']);assert.ok(!L.analyzeNotes('Accrued wages are recorded before payday.').matches.some(x=>x.id==='utilities'));});
test('focused reporting avoids demanding a full set of statements for a single introductory concept',()=>{const a=L.generateAssignment('Prepaid rent covers three months. Recognize coverage as it is used.',{id:'focused-report'}),s=L.expected(a,L.defaultEpisodeChoice(a),business);assert.equal(a.report,'topic');assert.equal(s.effects.length,3);assert.ok(!s.effects.some(e=>e.key==='equity'));assert.equal(L.checkAssignment({...a,needsRegeneration:true}),false);});
test('combined credit purchases, supplies counts and accruals share consistent records and ledger totals',()=>{for(let i=0;i<100;i++){const ids=Object.keys(L.concepts).sort((a,b)=>((i+a.charCodeAt(0)*17)%41)-((i+b.charCodeAt(0)*17)%41)).slice(0,6),a=L.generateAssignment('Combined introductory concepts for financial statements.',{id:'combination-'+i,concepts:ids,report:'statements',depth:'extended'}),s=L.expected(a,L.defaultEpisodeChoice(a),business),b=L.balances(s,postings(s)),f=Object.fromEntries(s.effects.map(e=>[e.key,e.value]));assert.ok(Math.abs(f.assets-f.liabilities-f.equity)<.01);const count=s.events.find(e=>e.id==='supplies-count');if(count)assert.equal(count.detail.lines.find(([k])=>k==='Ending supplies on hand at cost')[1],b.Supplies);assert.ok(b.Cash>=0);}});
