const financialRender=render;
const financialStart=start;
start=function(){financialStart();document.querySelectorAll('dialog[open]').forEach(d=>d.close());introTour();};
function monthName(n){return new Date(2026,n-1,1).toLocaleDateString('en-US',{month:'long',year:'numeric'});}
function documentKind(d){if(d.correction)return 'Audit memorandum';if(d.expectedRows)return 'Year-end closing worksheet';if(['Owner Capital','Investor Capital'].includes(d.credit))return 'Bank deposit slip';if(d.debit==='Prepaid Rent'||d.debit==='Rent Expense'&&d.credit==='Cash')return 'Rent payment receipt';if(d.debit==='Equipment')return 'Supplier invoice';if(d.debit==='Supplies')return 'Supplier receipt';if(d.debit==='Advertising Expense')return 'Advertising invoice';if(d.debit==='Accounts Receivable')return 'Customer invoice';if(d.credit==='Accounts Receivable')return 'Customer remittance';if(d.credit==='Sales Revenue')return 'Daily sales summary';if(d.credit==='Supplies')return 'Stock usage report';if(d.credit==='Prepaid Rent')return 'Rental coverage schedule';if(d.debit==='Depreciation Expense')return 'Fixed asset schedule';if(d.debit==='Fine Expense')return 'Penalty payment receipt';return 'Business record';}
function sourceDocument(d){const kind=documentKind(d),date=d.date||transactionDate(d.month||periodInfo().number),id=d.docId||'AUDIT',name=esc(state.name);let issuer='Neighborhood Bank',label='Deposit amount',description='Business opening deposit',status='Funds received',details='',amount=money(d.amount),party=`Account holder: ${name}`;
if(d.credit==='Owner Capital'){description='Funds contributed by business owner';details='<p>Depositor: business owner<br>Deposit method: bank transfer<br>Reference: opening business funds</p>';}
else if(d.debit==='Equipment'){issuer='Northside Business Equipment';label='Invoice total';description='Business equipment · delivered and placed in service';status='PAID';details='<p>Payment method: business bank payment<br>Delivery date: '+date+'<br>Terms: payment on delivery</p>';}
else if(d.debit==='Supplies'){issuer='Market Street Supply Co.';label='Receipt total';description='Consumable supplies · delivered to business storage';status='PAID';details='<p>Payment method: business bank payment<br>Order status: delivered</p>';}
else if(d.debit==='Advertising Expense'){issuer='Local Reach Media';label='Invoice total';description='Neighborhood advertising campaign';status='PAID';details='<p>Campaign period: '+monthName(d.month||periodInfo().number)+'<br>Payment method: business bank payment<br>Campaign delivered during the current month.</p>';}
else if(d.debit==='Prepaid Rent'||d.debit==='Rent Expense'&&d.credit==='Cash'){issuer='Oak Street Property Management';label='Payment received';description='Commercial workspace rental';status='PAID';const months=d.coverageMonths||(d.debit==='Prepaid Rent'?Number(d.text?.match(/covering (\d+) months/)?.[1]||1):1);const start=d.month||periodInfo().number;const end=Math.min(12,start+months-1);details=`<p>Tenant: ${name}<br>Coverage: ${monthName(start)}${months>1?' through '+monthName(end):''}<br>Monthly rental rate: ${money(d.monthlyRate||d.amount/months)}<br>Payment method: business bank payment</p>`;}
else if(d.debit==='Accounts Receivable'){issuer=state.name;party='Bill to: Neighborhood customers · monthly account sales';label='Amount due';description='Services delivered during '+monthName(d.month||periodInfo().number);status='UNPAID';const due=new Date(2026,d.month||periodInfo().number,15).toISOString().slice(0,10);details='<p>Service status: completed<br>Terms: payment in the following month<br>Due date: '+due+'<br>Payments received on this invoice: $0.00</p>';}
else if(d.credit==='Accounts Receivable'){issuer='Neighborhood Bank';label='Payment received';description='Customer payment against prior invoices';status='RECEIVED';details='<p>Transfer description: settlement of existing customer balances<br>New services included in this transfer: none<br>Deposited into: business checking</p>';}
else if(d.credit==='Sales Revenue'){issuer=state.name;label='Collected from customers';description='Completed services paid at time of sale';status='CASH SETTLED';details='<p>Reporting period: '+monthName(d.month||periodInfo().number)+'<br>Payment destination: business checking<br>Customer account charges: excluded from this summary</p>';}
else if(d.credit==='Supplies'){issuer=state.name+' · Operations';label='Cost of stock consumed';description='Materials issued and used to deliver customer services';status='INTERNAL';details='<p>Reporting period: '+monthName(d.month||periodInfo().number)+'<br>Stock valuation: purchase cost<br>New purchases: excluded<br>Issued supplies were consumed, not returned to storage.</p>';}
else if(d.credit==='Prepaid Rent'){issuer='Oak Street Property Management';label='Value of coverage used';description='Current month’s occupied workspace';status='NO PAYMENT DUE';details='<p>Coverage month: '+monthName(d.month||periodInfo().number)+'<br>Payment: previously received in advance<br>Current month cash charged: $0.00<br>Coverage consumed: one month</p>';}
else if(d.debit==='Depreciation Expense'){issuer=state.name+' · Asset register';label='Depreciation method';amount='Straight-line';description='Equipment in service at December 31, 2026';status='YEAR-END';details='<p>Useful life: 5 years · residual value: $0<br>Convention: full months, beginning with purchase month<br>No prior depreciation has been recorded this year.</p><table><thead><tr><th>Acquired</th><th>Cost</th><th>Months in use</th></tr></thead><tbody>'+state.documents.filter(x=>x.debit==='Equipment').map(x=>`<tr><td>${esc(x.date)}</td><td>${money(x.amount)}</td><td>${13-Number(x.date?.slice(5,7)||x.month)}</td></tr>`).join('')+'</tbody></table>';}
else if(d.expectedRows){issuer=state.name+' · Year-end records';label='Reporting date';amount='December 31';description=d.title;status='YEAR-END';details='<p>Year: September 1–December 31, 2026<br>Refer to the adjusted T accounts and annual financial statements.<br>Temporary accounts are closed through Income Summary into Owner Capital.</p>';}
else if(d.correction){issuer='Independent classroom auditor';label='Transaction value';description=d.title;status='REVIEW';details='<p>'+esc(d.text)+'</p>';}
else if(d.debit==='Fine Expense'){issuer='Classroom Audit Office';label='Penalty paid';description='Bookkeeping compliance penalty';status='PAID';details='<p>Payment method: business bank payment<br>Fictional classroom penalty; not a real regulatory fine.</p>';}
return `<article class="source-document"><div class="paper-top"><span>${esc(issuer)}</span><span class="paper-status">${status}</span></div><h2>${kind}</h2><div class="paper-meta"><span>Document ${esc(id)}</span><span>${esc(date)}</span></div><div class="paper-party">${party}</div><div class="paper-item">${esc(description)}</div>${details}<div class="paper-total"><span>${label}</span><strong>${amount}</strong></div><div class="paper-footer">${esc(issuer)} · Business copy · Retain with company records</div></article>`;}
function openRecord(d){let dialog=$('#document-modal');if(!dialog){dialog=document.createElement('dialog');dialog.id='document-modal';document.body.append(dialog);}dialog.innerHTML=sourceDocument(d)+`<div class="actions"><button id="work-record">Work on this entry</button><button class="secondary" id="close-document">Back to business</button></div>`;dialog.showModal();$('#close-document').onclick=()=>dialog.close();$('#work-record').onclick=()=>{dialog.close();state.pending=d;rows=[{account:'',debit:'',credit:''},{account:'',debit:'',credit:''}];message='';hint=false;save();render();$('.layout').children[1].scrollIntoView({behavior:'smooth',block:'start'});};}
render=function(){financialRender();if(!state){$('.welcome .tag').textContent='INTRODUCTION TO FINANCIAL ACCOUNTING';$('.welcome h1').innerHTML='Your first business.<br>Your first set of books.';$('.welcome p').textContent='Run a business for one year. Make decisions, interpret business documents, keep the books, and finish with annual financial statements and an audit.';return;}
const tools=$('.header-tools');const tour=document.createElement('button');tour.className='quiet';tour.textContent='Take a tour';tour.onclick=()=>introTour();tools.prepend(tour);if(view==='business'){const desk=$('.layout').children[1];desk.querySelector('h2').textContent='Business records';const d=state.pending;if(d){const event=desk.querySelector('.event');if(event){event.outerHTML=sourceDocument(d);const journalTitle=desk.querySelector('.tag');if(journalTitle)journalTitle.textContent='YOUR JOURNAL ENTRY';}}
document.querySelectorAll('[data-doc]').forEach(button=>{const doc=state.documents.find(d=>d.docId===button.dataset.doc);button.innerHTML=`<span>${esc(doc.date||'')}<br><strong>${documentKind(doc)}</strong><small>${esc(doc.title)}</small></span><span class="document-open">View document →</span>`;button.onclick=()=>openRecord(doc);});const prompt=desk.querySelector('.record-inbox>p');if(prompt)prompt.textContent='Open a document to inspect the transaction. You can record it now or leave it for later.';}}
introTour=function(index=0){if(!state)return;document.querySelectorAll('.tour-focus').forEach(e=>e.classList.remove('tour-focus'));$('#tour-overlay')?.remove();document.querySelectorAll('dialog[open]').forEach(d=>d.close());let dialog=$('#tour-dialog');if(!dialog){dialog=document.createElement('dialog');dialog.id='tour-dialog';document.body.append(dialog);}const steps=[['Run the business first','Your goal is to operate from September through December, prepare annual financial statements and closing entries, and pass the final audit. You can make purchases before posting their journal entries.','BUSINESS → RECORDS → REPORTS'],['Prepare to open','Choose a rent budget, buy equipment and supplies, and advertise. Read payment terms carefully: rent paid for future months is different from rent used this month.','Rent · Equipment · Supplies · Advertising'],['Read the documents','Open an item under Business records to see the invoice, receipt, deposit slip or sales report. Look for who paid, what was delivered, the dates, and whether payment is still due.','Date · Description · Payment status · Amount'],['Keep and check the books','Choose Work on this entry to write the journal entry. Your general ledger uses T accounts. Compare Cash with the bank statement and account for payments that have not cleared.','Business records → T accounts → Bank reconciliation'],['Finish the month and the year','Prepare monthly statements after recording the transactions and reconciling the bank. In December, complete depreciation, annual statements, closing entries, and the year-end audit.','12 months · Annual statements · Final audit']];const [title,text,caption]=steps[index];dialog.innerHTML=`<div class="tag">GETTING STARTED · ${index+1} OF ${steps.length}</div><h2>${title}</h2><div class="tour-example">${caption}</div><p>${text}</p><div class="tour-dots">${steps.map((_,i)=>`<span class="${i===index?'current':''}"></span>`).join('')}</div><div class="actions">${index?'<button class="secondary" id="tour-back">Back</button>':''}<button id="tour-next">${index===steps.length-1?'Start running my business':'Next →'}</button><button class="quiet" id="tour-skip">Skip tour</button></div>`;dialog.showModal();const finish=()=>{dialog.close();state.tourDone=true;save();};$('#tour-next').onclick=()=>{if(index===steps.length-1)finish();else introTour(index+1);};if($('#tour-back'))$('#tour-back').onclick=()=>introTour(index-1);$('#tour-skip').onclick=finish;dialog.oncancel=()=>{state.tourDone=true;save();};};
showHelp=function(){if(state)introTour();else alert('Name your business and select Start. A guided tour will explain the business records and accounting workflow.');};
render();if(state&&!state.tourDone)introTour();
