(function(root){
const topics={prepaid:{name:'Prepaid expenses',goal:'Distinguish paying for future benefits from using those benefits.',effect:'Show rent used this month and rent remaining for future months.'},receivables:{name:'Credit sales & collections',goal:'Separate earning revenue from collecting a customer payment.',effect:'Show revenue earned, cash received, and the customer balance still owed.'},equipment:{name:'Equipment & depreciation',goal:'Separate buying a long-lived asset from allocating its cost over time.',effect:'Show equipment cost, depreciation expense, and net equipment value.'},capital:{name:'Owner investment & cash expenses',goal:'Distinguish owner contributions from revenue and business expenses.',effect:'Show contributed capital, cash remaining, and expenses incurred.'}};
const accounts=['Prepaid Insurance','Supplies','Accounts Payable','Wages Payable','Unearned Revenue','Notes Payable','Interest Payable','Owner Drawings','Insurance Expense','Supplies Expense','Wages Expense','Utilities Expense','Interest Expense','Cash','Accounts Receivable','Prepaid Rent','Equipment','Accumulated Depreciation','Owner Capital','Sales Revenue','Rent Expense','Depreciation Expense','Advertising Expense'];
const cents=n=>Math.round(n*100)/100;
const D=root.BusinessDecisions||(typeof require==='function'?require('./business-decisions'):null);
function checkAssignment(a){if(a?.grading&&(!['latest','first'].includes(a.grading.attempt)||!a.grading.weights||!['account','amount','date'].every(k=>Number.isFinite(a.grading.weights[k])&&a.grading.weights[k]>=0&&a.grading.weights[k]<=100)||Math.abs(['account','amount','date'].reduce((n,k)=>n+a.grading.weights[k],0)-100)>.001))return false;if(!a||![1,2,3].includes(a.version)||!(a.version===3?a.topic==='custom':a.version===1?Object.hasOwn(topics,a.topic):Object.hasOwn(concepts,a.topic))||typeof a.id!=='string'||!a.id.trim()||a.id.length>100||typeof a.title!=='string'||!a.title.trim()||a.title.length>160||typeof a.instructions!=='string'||a.instructions.length>10000||!Number.isInteger(a.year)||a.year<2020||a.year>2100||!Number.isInteger(a.month)||a.month<1||a.month>12||!['guided','independent'].includes(a.support))return false;if(a.version===3&&(!['topic','statements'].includes(a.report)||!validGenerated(a)||(a.interactive&&!D.valid(a))))return false;if(a.version===2&&(a.needsRegeneration||!['topic','statements'].includes(a.report)||!Array.isArray(a.concepts)||a.concepts.length<1||a.concepts.length>6||new Set(a.concepts).size!==a.concepts.length||!a.concepts.every(x=>Object.hasOwn(concepts,x))||a.topic!==a.concepts[0]||!['focused','standard','extended'].includes(a.depth)||!Number.isInteger(a.seed)||a.seed<0||a.seed>4294967295||!Array.isArray(a.source)||a.source.length>6||a.source.some(x=>!x||!a.concepts.includes(x.id)||typeof x.evidence!=='string'||x.evidence.length>650)))return false;return typeof a.course==='string'&&a.course.length<=120&&typeof a.notes==='string'&&a.notes.length<=30000;}
function suggestTopic(notes){const t=notes.toLowerCase();return /prepaid|prepayment|rent in advance|unexpired/.test(t)?'prepaid':/depreciation|useful life|salvage|long.lived/.test(t)?'equipment':/receivable|credit sale|on account|customer payment/.test(t)?'receivables':'capital';}
function day(a,d){return `${a.year}-${String(a.month).padStart(2,'0')}-${String(d).padStart(2,'0')}`;}
function finalStage(a){return a.version===3&&(a.periodMonths||1)>1?a.periodMonths*2-1:2;}
function finalDate(a){const m=a.month+(a.periodMonths||1)-1;return `${a.year}-${String(m).padStart(2,'0')}-${new Date(Date.UTC(a.year,m,0)).getUTCDate()}`;}
function end(a){return new Date(Date.UTC(a.year,a.month,0)).getUTCDate();}
function expected(a,choice,business){if(a.version===3)return generatedScenario(a,choice,business);if(a.version===2)return expectedEpisode(a,choice,business);const opening=a.topic==='capital'?0:8000;let events=[],decision='',prediction={},effects=[];const event=(id,title,kind,date,amount,debit,credit,detail)=>events.push({id,title,kind,date,amount:cents(amount),debit,credit,detail});
if(a.topic==='prepaid'){const rate=[150,250,400][choice.location],months=choice.months;if(!rate||![1,3,6].includes(months))throw Error('Invalid rental choice');decision=`${['Quiet side street','Neighborhood main street','Town center'][choice.location]}, ${months} month${months===1?'':'s'} paid in advance`;event('payment','Commercial lease payment','lease',day(a,1),rate*months,'Prepaid Rent','Cash',{rate,months,location:choice.location});event('adjustment','Month-end rental coverage','coverage',day(a,end(a)),rate,'Rent Expense','Prepaid Rent',{rate,months});prediction={prompt:'At month-end, how much of the payment has the business used?',options:['One month of coverage','All of the prepaid coverage','None of the coverage'],correct:0,feedback:'One month of time has passed. The unused coverage remains an asset, regardless of how many months were paid for.'};effects=[{key:'expense',label:'Rent expense for the month',value:rate},{key:'remaining',label:'Prepaid rent remaining',value:rate*(months-1)},{key:'cash',label:'Ending cash',value:opening-rate*months}];}
if(a.topic==='receivables'){const sale=[400,700,1000][choice.order],paid=cents(sale*[.25,.5,1][choice.collection]);if(!sale||![0,1,2].includes(choice.collection))throw Error('Invalid customer choice');decision=`${['Small','Medium','Large'][choice.order]} customer order; ${[25,50,100][choice.collection]}% collected this month`;event('sale','Customer order completed','invoice',day(a,8),sale,'Accounts Receivable','Sales Revenue',{sale});event('collection','Customer payment received','remittance',day(a,22),paid,'Cash','Accounts Receivable',{sale,paid});prediction={prompt:'What happens to revenue when this customer pays an existing invoice?',options:['Revenue increases again','Revenue stays the same','Revenue decreases'],correct:1,feedback:'Revenue was earned when services were delivered. The later payment changes Cash and Accounts Receivable, without earning the revenue again.'};effects=[{key:'revenue',label:'Revenue earned this month',value:sale},{key:'remaining',label:'Customer balance remaining',value:sale-paid},{key:'cash',label:'Ending cash',value:opening+paid}];}
if(a.topic==='equipment'){const cost=[600,1200,1800][choice.level],life=[3,5,6][choice.life];if(!cost||!life)throw Error('Invalid equipment choice');const dep=cents(cost/life/12);decision=`${['Starter','Expanded','Professional'][choice.level]} equipment; ${life}-year useful-life estimate`;event('purchase','Equipment delivered and paid','equipment',day(a,1),cost,'Equipment','Cash',{cost,life});event('depreciation','Month-end asset register','asset',day(a,end(a)),dep,'Depreciation Expense','Accumulated Depreciation',{cost,life});prediction={prompt:'Does the month-end depreciation adjustment require a new cash payment?',options:['Yes, the full purchase price','Yes, the monthly depreciation amount','No new cash payment'],correct:2,feedback:'Cash was paid when the equipment was purchased. Depreciation allocates that recorded cost to periods of use; it is a noncash adjustment.'};effects=[{key:'expense',label:'Depreciation expense for one month',value:dep},{key:'remaining',label:'Net equipment value',value:cents(cost-dep)},{key:'cash',label:'Ending cash',value:opening-cost}];}
if(a.topic==='capital'){const investment=[3000,5000,7000][choice.investment],ad=[60,120,200][choice.ad];if(!investment||!ad)throw Error('Invalid funding choice');decision=`Owner contribution $${investment}; advertising package $${ad}`;event('investment','Owner funds deposited','deposit',day(a,1),investment,'Cash','Owner Capital',{investment});event('advertising','Advertising campaign delivered','advertising',day(a,10),ad,'Advertising Expense','Cash',{ad});prediction={prompt:'Does money contributed by the owner count as sales revenue?',options:['Yes, any cash received is revenue','No, it increases owner equity','Only if the business spends it'],correct:1,feedback:'The owner supplied capital rather than purchasing a service from the business. Cash and owner equity increase; revenue does not.'};effects=[{key:'capital',label:'Owner capital contributed',value:investment},{key:'expense',label:'Advertising expense',value:ad},{key:'cash',label:'Ending cash',value:investment-ad}];}
return {opening,events,decision,prediction,effects};}
function validateRows(rows,allowed=accounts){if(rows.length<2||rows.length>8)return 'Use between two and eight lines.';let d=0,c=0;for(const r of rows){if(!allowed.includes(r.account))return 'Choose an account for every line.';const debit=Number(r.debit||0),credit=Number(r.credit||0);if(!Number.isFinite(debit)||!Number.isFinite(credit)||debit<0||credit<0||(debit>0)===(credit>0))return 'Each line needs a positive debit or a positive credit.';d+=Math.round(debit*100);c+=Math.round(credit*100);}return d===c?null:'Debits and credits do not balance.';}
function assess(rows,date,e){const b={};for(const r of rows)b[r.account]=(b[r.account]||0)+Math.round((Number(r.debit||0)-Number(r.credit||0))*100);const used=Object.keys(b).filter(a=>b[a]!==0);const expected=e.lines?e.lines.reduce((out,x)=>(out[x.account]=(out[x.account]||0)+Math.round((x.debit-x.credit)*100),out),{}):{[e.debit]:Math.round(e.amount*100),[e.credit]:-Math.round(e.amount*100)};const required=Object.keys(expected).filter(k=>expected[k]!==0),account=used.length===required.length&&required.every(k=>used.includes(k));const amount=account&&required.every(k=>b[k]===expected[k]);return {account,amount,date:date===e.date,correct:account&&amount&&date===e.date};}
function balances(scenario,entries){if(scenario.accountList)return generatedBalances(scenario,entries);const b=Object.fromEntries(accounts.map(a=>[a,0]));b.Cash=scenario.opening;b['Owner Capital']=-scenario.opening;for(const e of Object.values(entries))for(const r of e.rows)b[r.account]+=Math.round((Number(r.debit||0)-Number(r.credit||0))*100)/100;return Object.fromEntries(Object.entries(b).map(([a,v])=>[a,cents(v)]));}
function grade(run){if(run.assignment?.version===3){let points=0;const weights=run.assignment.grading?.weights||{account:100/3,amount:100/3,date:100/3};const graded=run.scenario.events.filter(e=>!e.autoPosted);for(const e of graded){const saved=run.entries[e.id],g=run.assignment.grading?.attempt==='first'?run.first?.[e.id]:run.publicRun?run.assessments?.[e.id]:saved?assess(saved.rows,saved.date,e):null;if(g)points+=Number(g.account)*weights.account+Number(g.amount)*weights.amount+Number(g.date)*weights.date;}return {journal:graded.length?Math.round(points/graded.length):0,effects:0,prediction:0};}let journal=0;for(const e of run.scenario.events){const f=run.first[e.id];if(f)journal+=(f.account?1:0)+(f.amount?1:0)+(f.date?1:0);}return {journal:Math.round(80*journal/(run.scenario.events.length*3)),prediction:run.predictionFirst===run.scenario.prediction.correct?5:0,effects:run.effectsFirst?Math.round(15*run.scenario.effects.filter(e=>Math.abs(Number(run.effectsFirst[e.key])-e.value)<.005).length/run.scenario.effects.length):0};}
const businesses={
 'Coffee shop':{icon:'☕',description:'Espresso, pastries, and neighborhood regulars.',products:['Coffee & pastries','Specialty drinks','Catering coffee'],equipment:['Espresso machine & grinder','Espresso station & display case','Two-station café equipment'],supplies:'cups, napkins, and cleaning materials',customer:'a neighborhood office',order:'a catered coffee service'},
 'Design studio':{icon:'✦',description:'Brand identities, posters, and creative projects.',products:['Brand design','Print & illustration','Web design'],equipment:['Workstation & proof printer','Calibrated workstation & color printer','Two-workstation studio'],supplies:'paper, ink, and presentation materials',customer:'a local small business',order:'a completed design project'},
 'Bike repair':{icon:'🚲',description:'Tune-ups, repairs, and getting people moving.',products:['Commuter tune-ups','Family bike repairs','Performance servicing'],equipment:['Repair stand & tools','Two-bay workshop tools','Three-station workshop'],supplies:'lubricants, cleaning cloths, and workshop materials',customer:'a local cycling club',order:'a completed bicycle servicing package'},
 'Bakery':{icon:'🥐',description:'Fresh bread, custom cakes, and celebration orders.',products:['Bread & pastries','Custom cakes','Office catering'],equipment:['Mixer & baking oven','Commercial oven & mixer','Two-oven bakery setup'],supplies:'packaging, baking paper, and cleaning materials',customer:'a neighborhood event organizer',order:'a delivered bakery catering order'},
 'Plant shop':{icon:'❧',description:'Houseplants, thoughtful gifts, and greener spaces.',products:['Houseplants & gifts','Plant care services','Office plant styling'],equipment:['Display benches & potting tools','Display system & irrigation equipment','Workshop & display installation'],supplies:'pots, plant-care materials, and packaging',customer:'a local office manager',order:'a completed plant-styling service'},
 'Pet grooming':{icon:'🐾',description:'Baths, trims, and care for neighborhood pets.',products:['Bath & brush','Full grooming','Mobile grooming'],equipment:['Grooming table & dryer','Wash station & professional dryer','Two-station grooming setup'],supplies:'shampoo, towels, and cleaning materials',customer:'a neighborhood pet-care group',order:'a completed group grooming booking'},
 'Photography studio':{icon:'📷',description:'Portraits, product photos, and memorable events.',products:['Portraits','Product photography','Event photography'],equipment:['Camera & lighting kit','Studio camera & backdrop system','Two-camera studio setup'],supplies:'print paper, presentation folders, and studio materials',customer:'a local event organizer',order:'a delivered photography package'},
 'Fitness studio':{icon:'◎',description:'Small-group classes and personal coaching.',products:['Group classes','Personal training','Yoga & mobility'],equipment:['Mats & exercise equipment','Studio equipment & sound system','Expanded training equipment'],supplies:'sanitizing materials, towels, and class materials',customer:'a neighborhood employer',order:'a completed group training session'},
 'Bookshop':{icon:'📚',description:'Good books, neighborhood events, and reading clubs.',products:['Books & gifts','Reading events','Book-club services'],equipment:['Shelving & checkout station','Display shelving & checkout system','Event space & checkout equipment'],supplies:'bags, labels, and event materials',customer:'a community reading group',order:'a completed book-club event'},
 'Cleaning service':{icon:'✧',description:'Homes, offices, and recurring cleaning visits.',products:['Home cleaning','Office cleaning','Move-in cleaning'],equipment:['Vacuum & cleaning tools','Commercial vacuum & floor equipment','Two-team cleaning equipment'],supplies:'cleaning solutions, gloves, and cloths',customer:'a local property manager',order:'a completed cleaning contract'}
};
D.configure(businesses);
const colors={sage:'#315b47',terracotta:'#985c47',blue:'#486c83',plum:'#765568',ochre:'#927035',charcoal:'#3e4945'};
const styles=['Classic awning','Modern studio','Garden storefront'];
const districts=['Neighborhood street','Downtown corner','Campus village'];
function normalizeBusiness(v){if(!v||typeof v.name!=='string'||!v.name.trim()||v.name.trim().length>45||!Object.hasOwn(businesses,v.type)||!Object.hasOwn(colors,v.color))throw Error('Check the business name, type, and color.');const definition=businesses[v.type];const style=v.style||styles[0],district=v.district||districts[0],specialty=v.specialty||definition.products[0],logo=v.logo||definition.icon,tagline=v.tagline||'';if(!styles.includes(style)||!districts.includes(district)||!definition.products.includes(specialty)||![definition.icon,'✦','●','❧','◇'].includes(logo)||typeof tagline!=='string'||tagline.length>70)throw Error('Choose valid business design options.');return {name:v.name.trim(),type:v.type,color:v.color,style,district,specialty,logo,tagline:tagline.trim()};}
const concepts={
 prepaid:{...topics.prepaid,pattern:/prepaid\s+rent|prepaid expenses|rent\s+(?:paid\s+)?in advance|unexpired\s+rent|prepay(?:ing|ment)?\s+(?:the\s+)?rent/i,decision:'Choose a location and rental coverage',question:'You pay for several months now. When does that coverage become an expense?',fields:[['location','Where will you rent?',['Side street · modest rent','Neighborhood center · larger space','Downtown · premium frontage']],[ 'months','How much coverage will you buy?',['1 month','3 months','6 months'],[1,3,6]]]},
 insurance:{name:'Prepaid insurance',goal:'Allocate an insurance premium between coverage used and coverage remaining.',pattern:/insurance|premium/i,decision:'Protect your business',question:'Coverage lasts beyond this month. How much remains a future benefit?',fields:[['plan','Choose coverage',['Essential protection','Standard protection','Expanded protection']],['term','Coverage period',['3 months','6 months','12 months'],[3,6,12]]]},
 supplies:{name:'Supplies & supplies used',goal:'Use a physical count to distinguish supplies held from supplies consumed.',pattern:/supplies|supply expense|physical count/i,decision:'Stock the workroom',question:'Some materials are still on the shelf. Should the whole purchase become an expense?',fields:[['package','Choose a supplies package',['Starter stock','Regular stock','Busy-month stock']],['usage','Expected level of activity',['Light use','Steady use','Busy use']]]},
 receivables:{...topics.receivables,pattern:/receivable|credit sale|sales?\s+on account|collection|customer payment/i,decision:'Accept a customer order',question:'Your customer pays an invoice later. Does that create new revenue?',fields:[['order','Choose the customer order',['Small booking','Standard booking','Large booking']],['collection','Agree a collection arrangement',['25% collected this month','50% collected this month','75% collected this month']]]},
 equipment:{...topics.equipment,pattern:/depreciation|useful life|salvage|residual value|equipment|long.lived/i,decision:'Equip your business',question:'The equipment will help for years. What belongs in this month’s expense?',fields:[['level','Choose your equipment',['Starter package','Expanded package','Professional package']],['life','Useful-life estimate',['3 years','5 years','6 years']]]},
 capital:{...topics.capital,pattern:/owner.{0,30}(invest|capital|contribut)|contributed capital|capital contribution|cash expense|advertising/i,decision:'Fund a local campaign',question:'An owner deposit and a customer payment both add cash. Why are they different?',fields:[['investment','Owner contribution',['Small contribution','Standard contribution','Larger contribution']],['ad','Advertising campaign',['Local listing','Neighborhood promotion','Community launch']]]},
 unearned:{name:'Customer deposits & earned revenue',goal:'Recognize an obligation when paid before delivery, then revenue as work is completed.',pattern:/unearned|deferred revenue|customer deposit|advance.{0,15}(customer|payment)|revenue.{0,15}advance/i,decision:'Plan a prepaid customer booking',question:'You receive payment before providing the service. Have you earned it yet?',fields:[['booking','Booking size',['Small booking','Standard booking','Large booking']],['delivery','Work completed by month-end',['25% delivered','50% delivered','75% delivered']]]},
 wages:{name:'Accrued wages',goal:'Recognize wages earned by employees even when payment follows in a later period.',pattern:/wages|salaries|payroll/i,decision:'Schedule support for the business',question:'An employee has worked but payday is next month. Which period bears the cost?',fields:[['staff','Choose a staffing arrangement',['Short shifts','Regular shifts','Expanded shifts']],['unpaid','Final unpaid workdays',['2 days','3 days','4 days'],[2,3,4]]]},
 utilities:{name:'Accrued operating expenses',goal:'Record an expense when services are used, not only when the bill is paid.',pattern:/utilities|utility|accrued (?:operating )?expense|electricity/i,decision:'Choose a workspace service plan',question:'The business used a service this month but pays next month. What needs recording?',fields:[['plan','Service plan',['Essential service','Standard service','Extended service']],['activity','Usage level',['Low usage','Regular usage','Busy usage']]]},
 payables:{name:'Credit purchases & supplier payments',goal:'Distinguish acquiring supplies on credit from later settling the supplier balance.',pattern:/accounts? payable|credit purchase|purchases?.{0,20}on account|supplier payment/i,decision:'Arrange supplies with a trade supplier',question:'Does paying an existing supplier invoice create another supplies purchase?',fields:[['package','Choose a materials order',['Starter order','Regular order','Larger order']],['payment','Supplier settlement this month',['25% paid','50% paid','75% paid']]]},
 borrowing:{name:'Notes payable & interest',goal:'Separate borrowed principal from revenue and recognize interest accrued over time.',pattern:/notes? payable|\bborrow(?:ing|ed)?\b|\bloan\b|\binterest\b/i,decision:'Arrange business financing',question:'Borrowing supplies cash. Does it increase profit?',fields:[['principal','Loan size',['Small loan','Standard loan','Larger loan']],['rate','Annual interest rate',['6%','9%','12%']]]},
 drawings:{name:'Owner withdrawals',goal:'Distinguish an owner’s personal withdrawal from a business expense.',pattern:/withdrawal|drawings|owner.{0,15}draw/i,decision:'Arrange an owner withdrawal',question:'Is a transfer to the owner for personal use part of operating expenses?',fields:[['amount','Personal withdrawal',['Small withdrawal','Standard withdrawal','Larger withdrawal']],['timing','Transfer date',['10th of the month','18th of the month','24th of the month']]]},
 cashsales:{name:'Cash revenue & operating expenses',goal:'Recognize delivered cash services and expenses for services consumed.',pattern:/cash sales?|cash revenue|service revenue|cash basis|revenue recognition/i,decision:'Plan a service day',question:'What separates an earned customer payment from owner funding?',fields:[['activity','Service volume',['Quiet week','Steady week','Busy week']],['promotion','Promotion expense',['Local listing','Neighborhood promotion','Community campaign']]]}
};
function hash(value){let h=2166136261;for(const c of value)h=Math.imul(h^c.charCodeAt(0),16777619);return h>>>0;}
function analyzeNotes(notes){const paragraphs=String(notes).split(/\n+|(?<=[.!?])\s+/).map(s=>s.trim()).filter(Boolean);const matches=Object.entries(concepts).map(([id,c])=>({id,name:c.name,evidence:paragraphs.filter(p=>c.pattern.test(p)).slice(0,2).join(' ').slice(0,650)})).filter(x=>x.evidence);const unsupported=[];const flags=[[/FIFO|LIFO|inventory|cost of goods sold/i,'Inventory valuation and cost of goods sold'],[/bond|amortization of.*discount|effective.interest/i,'Bonds and effective-interest amortization'],[/declining.balance|units.of.production/i,'Depreciation methods other than straight-line'],[/bank reconcili|outstanding check|deposit in transit/i,'Bank reconciliation'],[/closing entr|income summary/i,'Closing entries'],[/sales tax|VAT/i,'Sales tax'],[/bad debt|allowance for doubtful/i,'Bad-debt estimates'],[/dividend|common stock|retained earnings/i,'Corporate equity'],[/cash flow statement|statement of cash flows/i,'Full cash-flow statements']];for(const [p,label]of flags)if(p.test(notes))unsupported.push(label);return {matches,unsupported};}
function episodeTitle(notes,selected){const first=notes.trim().split(/[\n.!?]/)[0].trim();return first.length<=90&&/chapter|lesson|unit|week|topic|adjusting entries/i.test(first)?first:'A month of '+selected.slice(0,3).map(id=>({prepaid:'coverage',insurance:'protection',supplies:'resources',receivables:'customer promises',equipment:'investment',capital:'funding',unearned:'commitments',wages:'teamwork',utilities:'operations',borrowing:'financing',drawings:'owner decisions',payables:'supplier commitments',cashsales:'service'})[id]).join(', ');}
function generateAssignment(notes,options={}){if(typeof notes!=='string'||notes.trim().length<20||notes.length>30000)throw Error('Add at least a sentence of course notes (up to 30,000 characters).');const analysis=analyzeNotes(notes),selected=options.concepts||analysis.matches.map(x=>x.id);if(!selected.length)throw Error('No supported introductory accounting concepts were identified. Review the scope below or add clearer course notes.');if(selected.length>6)throw Error('Choose up to six concepts for one episode. Split broader notes into separate assignments.');const primary=selected[0],id=options.id||root.crypto.randomUUID(),source=analysis.matches.filter(x=>selected.includes(x.id));const a={version:2,id,topic:primary,title:options.title||episodeTitle(notes,selected),course:options.course||'Introduction to Financial Accounting',instructions:options.instructions||'Run your business through a new month. Make the operating choices, investigate the source records, prepare the journal, and report the month-end financial position.',year:options.year||2026,month:options.month||9,support:options.support||'guided',notes,concepts:selected,depth:options.depth||'standard',report:options.report||(/income statement|balance sheet|financial statements|accounting equation/i.test(notes)?'statements':'topic'),seed:hash(notes+'|'+id),source,excluded:analysis.unsupported,objectives:selected.map(x=>concepts[x].goal),published:false,origin:'Professor assignment'};if(!checkAssignment(a))throw Error('Check the selected concepts and assignment settings.');return a;}
function episodeChoices(a){return a.concepts.map(id=>({id,...concepts[id]}));}
function defaultEpisodeChoice(a){const choice={};for(const c of episodeChoices(a))for(const [field,,values,numbers]of c.fields)choice[c.id+'_'+field]=numbers?numbers[1]:1;return choice;}
function validEpisodeChoice(a,choice){return a.concepts.every(id=>concepts[id].fields.every(([field,,labels,numbers])=>{const v=choice[id+'_'+field];return Number.isInteger(v)&&(numbers||labels.map((_,i)=>i)).includes(v);}));}
const conceptChecks={
 payables:{options:['Yes; the materials are purchased again when paid.','No; payment reduces cash and the existing supplier liability.','Yes; supplier payments are always expenses.'],correct:1,feedback:'The purchase records supplies and accounts payable. Later payment settles the liability; it does not acquire the same materials again.'},
 prepaid:{options:['As each month of rental coverage is used.','Immediately, because the whole payment left the bank.','Only when the lease expires.'],correct:0,feedback:'Unused coverage remains an asset. Only the coverage used in this period becomes rent expense.'},
 insurance:{options:['Expense the full premium now.','Expense the portion of coverage used; keep the rest as prepaid insurance.','Record no insurance expense until the policy ends.'],correct:1,feedback:'Insurance expense follows the coverage used. Paying ahead creates a future benefit until that coverage is consumed.'},
 supplies:{options:['No; the physical count identifies what remains an asset.','Yes; any materials purchase is immediately an expense.','No; supplies never become expenses.'],correct:0,feedback:'Subtract supplies still on hand from supplies available. The used portion becomes expense; the remaining portion stays an asset.'},
 receivables:{options:['Yes, because the bank balance increased.','Only if the customer pays the entire invoice.','No; collection settles the receivable created by the completed sale.'],correct:2,feedback:'The invoice records earned revenue once. Collecting it exchanges a receivable for cash, without earning revenue again.'},
 equipment:{options:['The entire original purchase price.','One month of cost allocation, with no new cash payment.','Nothing, because equipment stays useful for years.'],correct:1,feedback:'Straight-line depreciation allocates equipment cost over its useful life. It is a noncash month-end adjustment.'},
 capital:{options:['Both are sales revenue.','Owner funding increases capital; completed customer services earn revenue.','Only owner funding counts as revenue.'],correct:1,feedback:'An owner contributes resources in their ownership role. A customer pays for delivered services. Those economic events affect different accounts.'},
 unearned:{options:['Yes; cash received always means revenue.','Only the deposit paid by bank transfer is revenue.','Not until the contracted service is delivered; advance payment creates a liability.'],correct:2,feedback:'Before delivery, the business owes service to the customer. Delivery fulfills that obligation and earns revenue.'},
 wages:{options:['This month; record the earned wages and the obligation to pay.','Next month, because that is payday.','Neither month until a bank statement arrives.'],correct:0,feedback:'Employee work creates an expense this month. The unpaid portion also creates wages payable.'},
 utilities:{options:['Only a note; no accounting until payment.','An expense for services used and a liability for the unpaid bill.','An asset and an owner contribution.'],correct:1,feedback:'A service used in this period is an expense of this period. Its unpaid bill is a liability even before cash is paid.'},
 borrowing:{options:['Yes; the received principal is profit.','Only half the loan counts as revenue.','No; principal creates a repayment obligation, and accrued interest is an expense.'],correct:2,feedback:'Borrowing increases cash and notes payable. Interest is the cost of financing; principal is not earned revenue.'},
 drawings:{options:['Yes; every cash payment is an expense.','No; a personal withdrawal reduces owner equity.','Yes; withdrawals are wages expense.'],correct:1,feedback:'A personal transfer to the owner is a drawing, not a cost of providing business services.'},
 cashsales:{options:['A customer payment for a delivered service earns revenue; owner funding adds capital.','Both are revenue because cash comes in.','Only an owner contribution earns revenue.'],correct:0,feedback:'The reason for the receipt determines its classification. Completed customer services earn revenue; owner investment supplies equity.'}
};

function expectedEpisode(a,choice,business={name:'Example Coffee',type:'Coffee shop'}){
 if(!checkAssignment(a)||!validEpisodeChoice(a,choice))throw Error('Choose valid business options.');const biz=businesses[business.type]||businesses['Coffee shop'],seed=hash(a.seed+'|'+business.name+'|'+business.type),factor=8+seed%5;const opening=24000+(seed%5)*500,events=[],decisions=[];const value=(id,key)=>choice[id+'_'+key];const add=(id,title,kind,date,amount,debit,credit,lines,stage=0)=>{if(amount<=0)return;events.push({id,title,kind,date,amount:cents(amount),debit,credit,stage,detail:{lines}});};const doc=(id,label,dayNum,amount,dr,cr,lines,stage=0)=>add(id,label,'episode',day(a,Math.min(dayNum,end(a))),amount,dr,cr,lines,stage);
 const terms=id=>{const c=concepts[id];decisions.push(c.name+': '+c.fields.map(([k,,labels,numbers])=>labels[(numbers||labels.map((_,i)=>i)).indexOf(value(id,k))]).join(' · '));};
 for(const id of a.concepts){const factor=8+(hash(seed+'|'+id)%81)/10;terms(id);
 if(id==='prepaid'){const rate=(value(id,'location')+1)*factor*25,months=value(id,'months');doc('rent-payment','Rental payment receipt',1,rate*months,'Prepaid Rent','Cash',[['Supplier','Oak Street Property Management'],['Location',['Side street','Neighborhood center','Downtown'][value(id,'location')]],['Coverage begins',day(a,1)],['Monthly rate',rate],['Coverage purchased',months+' months'],['Settlement','Paid from business checking']]);doc('rent-used','Lease occupancy schedule',end(a),rate,'Rent Expense','Prepaid Rent',[['Coverage starts',day(a,1)],['Paid coverage',months+' months'],['Monthly rate',rate],['Occupancy this period','1 full month'],['Additional payment due',0]],2);}
 if(id==='insurance'){const rate=(value(id,'plan')+1)*factor*10,term=value(id,'term');doc('insurance-payment','Insurance policy receipt',1,rate*term,'Prepaid Insurance','Cash',[['Provider','Harbor Mutual'],['Coverage begins',day(a,1)],['Monthly premium',rate],['Policy duration',term+' months'],['Settlement','Paid in full']]);doc('insurance-used','Policy coverage summary',end(a),rate,'Insurance Expense','Prepaid Insurance',[['Monthly premium',rate],['Coverage used','1 full month'],['Policy duration',term+' months'],['New premium due',0]],2);}
 if(id==='supplies'){const cost=(value(id,'package')+1)*factor*40,used=cents(cost*[.25,.5,.75][value(id,'usage')]);doc('supplies-purchase','Workroom materials receipt',3,cost,'Supplies','Cash',[['Supplier','Neighborhood Trade Supply'],['Materials',biz.supplies],['Settlement','Paid from business checking']]);doc('supplies-count','Physical supplies count',end(a),used,'Supplies Expense','Supplies',[['Materials',biz.supplies],['Beginning supplies',0],['Supplies purchased',cost],['Ending supplies on hand at cost',cost-used],['Counted by','Operations team']],2);if(a.depth!=='focused'){const topUp=cents(cost*.2);doc('supplies-topup','Additional materials receipt',16,topUp,'Supplies','Cash',[['Materials',biz.supplies],['Reason','Reserve supplies for next month'],['Settlement','Paid in full'],['Count note','This sealed reserve is included in the month-end count']],1);events.find(e=>e.id==='supplies-count').detail.lines[3][1]=cents(cost-used+topUp);events.find(e=>e.id==='supplies-count').detail.lines[2][1]=cents(cost+topUp);}}
 if(id==='receivables'){const sale=(value(id,'order')+1)*factor*80,paid=cents(sale*[.25,.5,.75][value(id,'collection')]);doc('customer-invoice','Completed customer order invoice',8,sale,'Accounts Receivable','Sales Revenue',[['Customer',biz.customer],['Service',biz.order],['Delivered',day(a,8)],['Invoice amount',sale],['Payment terms','Partial settlement on the 22nd'],['Cash received on delivery',0]],1);doc('customer-payment','Customer remittance advice',22,paid,'Cash','Accounts Receivable',[['Sender',biz.customer],['Original invoice date',day(a,8)],['Original invoice amount',sale],['Transfer received',paid],['Purpose','Settlement of existing invoice; no new delivery']],1);if(a.depth==='extended'){const next=cents(sale*.5);doc('second-invoice','Second completed customer order',26,next,'Accounts Receivable','Sales Revenue',[['Customer','Another local business'],['Service',biz.order],['Delivery',day(a,26)],['Terms','Payment due next month'],['Cash received',0]],1);}}
 if(id==='equipment'){const cost=(value(id,'level')+1)*factor*100,life=[3,5,6][value(id,'life')],dep=cents(cost/life/12);doc('equipment-purchase','Equipment supplier invoice',1,cost,'Equipment','Cash',[['Supplier','Northside Business Equipment'],['Equipment',biz.equipment[value(id,'level')]],['In service',day(a,1)],['Settlement','Paid in full']]);doc('asset-register','Month-end fixed asset register',end(a),dep,'Depreciation Expense','Accumulated Depreciation',[['Equipment',biz.equipment[value(id,'level')]],['Original cost',cost],['Useful life',life+' years'],['Residual value',0],['Method','Straight-line'],['Time in service','1 full month'],['Cash payable now',0]],2);}
 if(id==='capital'){const capital=(value(id,'investment')+1)*factor*200,ad=(value(id,'ad')+1)*factor*12;doc('owner-deposit','Owner contribution deposit slip',1,capital,'Cash','Owner Capital',[['Depositor','Business owner'],['Purpose','Additional owner investment'],['Funds received',capital],['Customer goods or services','None']]);doc('advertising-invoice','Delivered advertising campaign',12,ad,'Advertising Expense','Cash',[['Supplier','Local Reach Media'],['Campaign',business.specialty||biz.products[0]],['Service status','Delivered during this month'],['Settlement','Paid in full']],1);}
 if(id==='unearned'){const amount=(value(id,'booking')+1)*factor*100,earned=cents(amount*[.25,.5,.75][value(id,'delivery')]);doc('booking-deposit','Advance booking payment',5,amount,'Cash','Unearned Revenue',[['Customer',biz.customer],['Booking',biz.order],['Total advance received',amount],['Delivery on payment date','None'],['Contract terms','Recognize delivery as completed']]);doc('booking-progress','Customer delivery acceptance',end(a),earned,'Unearned Revenue','Sales Revenue',[['Original customer advance',amount],['Service',biz.order],['Delivery completed this month',[25,50,75][value(id,'delivery')]+'%'],['Remaining delivery','Scheduled for next month'],['New customer payment',0]],2);}
 if(id==='wages'){const daily=(value(id,'staff')+1)*factor*8,unpaid=value(id,'unpaid'),paid=daily*8;doc('payroll-payment','Payroll payment confirmation',15,paid,'Wages Expense','Cash',[['Employee','Business support assistant'],['Daily wage',daily],['Paid workdays',8],['Settlement','Paid from business checking']],1);doc('payroll-accrual','Unpaid timesheet summary',end(a),daily*unpaid,'Wages Expense','Wages Payable',[['Daily wage',daily],['Additional workdays this month',unpaid],['Payment date','Next month'],['Current payment',0]],2);}
 if(id==='utilities'){const amount=(value(id,'plan')+1)*(value(id,'activity')+2)*factor*6;doc('utility-accrual','Workspace utility service bill',end(a),amount,'Utilities Expense','Accounts Payable',[['Provider','City Utility Services'],['Service period',day(a,1)+' through '+day(a,end(a))],['Amount billed',amount],['Payment due','15th of next month'],['Current payment',0]],2);if(a.depth!=='focused'){const paid=cents(amount*.4);doc('utility-paid','Paid workspace service receipt',14,paid,'Utilities Expense','Cash',[['Provider','City Utility Services'],['Service','One-time service used this month'],['Settlement','Paid in full']],1);}}
 if(id==='payables'){const cost=(value(id,'package')+1)*factor*45,paid=cents(cost*[.25,.5,.75][value(id,'payment')]);doc('supplier-invoice','Trade supplier materials invoice',4,cost,'Supplies','Accounts Payable',[['Supplier','Neighborhood Trade Supply'],['Materials',biz.supplies],['Delivered',day(a,4)],['Invoice amount',cost],['Terms','Partial payment this month; remainder next month'],['Payment on delivery',0]]);doc('supplier-payment','Supplier payment confirmation',23,paid,'Accounts Payable','Cash',[['Supplier','Neighborhood Trade Supply'],['Original invoice date',day(a,4)],['Original invoice amount',cost],['Payment sent',paid],['New materials with this payment','None']],1);}
 if(id==='borrowing'){const principal=(value(id,'principal')+1)*factor*250,rate=[6,9,12][value(id,'rate')],interest=cents(principal*rate/100/12);doc('loan-received','Business loan disbursement',1,principal,'Cash','Notes Payable',[['Lender','Neighborhood Bank'],['Principal received',principal],['Annual interest rate',rate+'%'],['Term','Principal due in one year'],['Interest convention','Annual rate / 12; full calendar month']]);doc('interest-accrual','Loan interest statement',end(a),interest,'Interest Expense','Interest Payable',[['Principal outstanding',principal],['Annual rate',rate+'%'],['Time outstanding','1 full month'],['Interest payment due','Next month'],['Principal payment this month',0]],2);}
 if(id==='drawings'){const amount=(value(id,'amount')+1)*factor*35;doc('owner-withdrawal','Owner personal transfer', [10,18,24][value(id,'timing')],amount,'Owner Drawings','Cash',[['Recipient','Business owner'],['Purpose','Personal use'],['Business services received','None'],['Transfer status','Completed']],1);}
 if(id==='cashsales'){const sale=(value(id,'activity')+1)*factor*90,ad=(value(id,'promotion')+1)*factor*10;doc('cash-service','Completed service cash receipt',12,sale,'Cash','Sales Revenue',[['Customer','Walk-in customers'],['Service',biz.order],['Delivery status','Completed'],['Payment','Received in business checking']],1);doc('cash-ad','Local campaign receipt',7,ad,'Advertising Expense','Cash',[['Supplier','Local Reach Media'],['Service','Local campaign delivered this month'],['Payment','Paid in full']]);if(a.depth!=='focused'){const more=cents(sale*.6);doc('cash-service-2','Second service cash receipt',24,more,'Cash','Sales Revenue',[['Customer','Walk-in customers'],['Service',biz.order],['Delivery status','Completed'],['Payment','Received in business checking']],1);}}
 }
 // The physical count includes all materials delivered, including credit purchases.
 const count=events.find(e=>e.id==='supplies-count');if(count){const available=events.filter(e=>e.debit==='Supplies').reduce((n,e)=>n+e.amount,0);count.detail.lines.find(([key])=>key==='Supplies purchased')[1]=cents(available);count.detail.lines.find(([key])=>key==='Ending supplies on hand at cost')[1]=cents(available-count.amount);}
 // A trading-only lesson still opens with a decision record; it never needs a JE to move forward.
 if(!events.some(e=>e.stage===0))events[0].stage=0;
 events.sort((x,y)=>x.stage-y.stage||x.date.localeCompare(y.date)||x.id.localeCompare(y.id));
 const scenario={opening,events,decision:decisions.join(' / '),decisions,stages:['Set up the month','Operate the business','Close the books'],prediction:{prompt:concepts[a.concepts[0]].question,...conceptChecks[a.concepts[0]]},effects:[]};
 const entries=Object.fromEntries(events.map(e=>[e.id,{rows:[{account:e.debit,debit:e.amount},{account:e.credit,credit:e.amount}]}])),b=balances(scenario,entries),revenue=-b['Sales Revenue'],expense=accounts.filter(x=>x.endsWith('Expense')).reduce((sum,x)=>sum+b[x],0),assets=b.Cash+b['Accounts Receivable']+b['Prepaid Rent']+b['Prepaid Insurance']+b.Supplies+b.Equipment+b['Accumulated Depreciation'],liabilities=-(b['Accounts Payable']+b['Wages Payable']+b['Unearned Revenue']+b['Notes Payable']+b['Interest Payable']),equity=-b['Owner Capital']-b['Owner Drawings']+revenue-expense;
 scenario.effects=[{key:'cash',label:'Ending cash',value:b.Cash},{key:'revenue',label:'Revenue earned',value:cents(revenue)},{key:'expense',label:'Total expenses',value:cents(expense)},{key:'profit',label:'Net income (loss)',value:cents(revenue-expense)},{key:'assets',label:'Total assets',value:cents(assets)},{key:'liabilities',label:'Total liabilities',value:cents(liabilities)},{key:'equity',label:'Ending owner equity',value:cents(equity)}];if(a.report==='topic'){const scoped={payables:[['Accounts payable outstanding',-b['Accounts Payable']],['Supplies acquired and still held',b.Supplies]],prepaid:[['Prepaid rent remaining',b['Prepaid Rent']],['Rent expense',b['Rent Expense']]],insurance:[['Prepaid insurance remaining',b['Prepaid Insurance']],['Insurance expense',b['Insurance Expense']]],supplies:[['Supplies remaining',b.Supplies],['Supplies expense',b['Supplies Expense']]],receivables:[['Customer receivables outstanding',b['Accounts Receivable']],['Revenue earned',-b['Sales Revenue']]],equipment:[['Equipment net book value',cents(b.Equipment+b['Accumulated Depreciation'])],['Depreciation expense',b['Depreciation Expense']]],capital:[['Owner capital including verified opening balance',-b['Owner Capital']],['Advertising expense',b['Advertising Expense']]],unearned:[['Undelivered customer obligations',-b['Unearned Revenue']],['Revenue earned',-b['Sales Revenue']]],wages:[['Wages expense',b['Wages Expense']],['Wages still payable',-b['Wages Payable']]],utilities:[['Utilities expense',b['Utilities Expense']],['Accounts payable outstanding',-b['Accounts Payable']]],borrowing:[['Loan principal outstanding',-b['Notes Payable']],['Interest still payable',-b['Interest Payable']]],drawings:[['Owner withdrawals',b['Owner Drawings']],['Owner capital less withdrawals',cents(-b['Owner Capital']-b['Owner Drawings'])]],cashsales:[['Revenue earned',-b['Sales Revenue']],['Advertising expense',b['Advertising Expense']]]};scenario.effects=[{key:'cash',label:'Ending cash',value:b.Cash},...a.concepts.flatMap(id=>scoped[id].map(([label,value],i)=>({key:id+'_'+i,label,value:cents(value)})))];}return scenario;
}
function pendingDecision(r){if(!r.assignment.interactive)return null;const stage=r.stage||0;return r.assignment.interactive.controls.some(c=>D.controlStage(r.assignment,c)===stage)&&!(r.decidedStages||[...(r.decidedMonths||[0]).map(m=>m*2)]).includes(stage)?stage:null;}
function decisionControls(r){return r.assignment.interactive.controls.filter(c=>D.controlStage(r.assignment,c)===(r.stage||0));}
function pendingMonth(r){const stage=pendingDecision(r);return stage===null?null:Math.floor(stage/2);}
function availableEvents(r){const pending=pendingDecision(r);return r.assignment.version>=2?r.scenario.events.filter(e=>e.stage<=(r.stage||0)&&(pending===null||e.stage<pending)):(r.advanced?r.scenario.events:r.scenario.events.slice(0,1));}

function topic(a){if(a.version===3)return {name:'Course assignment',goal:a.objectives.join(' '),effect:'Report the financial results using your accounts.'};return (a.version===2?concepts:topics)[a.topic];}
function validGenerated(a){try{return validateGenerated(a);}catch{return false;}}
function validateGenerated(a){if(typeof a.notes!=='string'||(a.periodMonths!==undefined&&(!Number.isInteger(a.periodMonths)||a.periodMonths<1||a.periodMonths>4||a.month+a.periodMonths-1>12)))return false;const b=a.blueprint,types=['asset','contraasset','liability','equity','contraequity','revenue','expense'];if(!b||!Array.isArray(b.accounts)||b.accounts.length<3||b.accounts.length>24||!Array.isArray(b.opening)||!Array.isArray(b.paths)||b.paths.length!==3||!Array.isArray(a.objectives)||a.objectives.length<1||a.objectives.length>6||a.objectives.some(x=>typeof x!=='string'||x.length>400)||!Array.isArray(a.source)||a.source.length<1||a.source.length>6||a.source.some(x=>typeof x.evidence!=='string'||!x.evidence.trim()||x.evidence.length>650||!a.notes.includes(x.evidence)))return false;
 const names=b.accounts.map(x=>x?.name);if(new Set(names).size!==names.length||b.accounts.some(x=>typeof x.name!=='string'||!x.name.trim()||x.name.length>60||['__proto__','constructor','prototype'].includes(x.name)||!types.includes(x.type))||!names.includes('Cash'))return false;
 const rows=rs=>Array.isArray(rs)&&rs.length>=2&&rs.length<=8&&rs.every(x=>x&&typeof x.account==='string'&&names.includes(x.account)&&typeof x.debit==='number'&&typeof x.credit==='number'&&Number.isFinite(x.debit)&&Number.isFinite(x.credit)&&x.debit>=0&&x.credit>=0&&x.debit<=1e6&&x.credit<=1e6&&Math.abs(x.debit*100-Math.round(x.debit*100))<1e-6&&Math.abs(x.credit*100-Math.round(x.credit*100))<1e-6&&((x.debit>0)!==(x.credit>0)))&&Math.round(rs.reduce((n,x)=>n+x.debit-x.credit,0)*100)===0;
 if(b.opening.length&& !rows(b.opening))return false;
 return b.paths.every((p,i)=>p&&p.id===String(i)&&typeof p.label==='string'&&p.label.length<=100&&typeof p.description==='string'&&p.description.length<=1200&&Array.isArray(p.events)&&p.events.length>=2&&p.events.length<=18&&new Set(p.events.map(e=>e.id)).size===p.events.length&&p.events.some(e=>e.stage===0)&&p.events.some(e=>e.stage===finalStage(a))&&p.events.every(e=>typeof e.id==='string'&&/^[a-z0-9-]{1,60}$/.test(e.id)&&typeof e.title==='string'&&e.title.length<=120&&Number.isInteger(e.stage)&&e.stage>=0&&e.stage<=finalStage(a)&&e.date>=day(a,1)&&e.date<=finalDate(a)&&/^\d{4}-\d{2}-\d{2}$/.test(e.date)&&!Number.isNaN(Date.parse(e.date))&&e.document&&typeof e.document.issuer==='string'&&e.document.issuer.length<=120&&typeof e.document.status==='string'&&e.document.status.length<=50&&Array.isArray(e.document.fields)&&e.document.fields.length>=3&&e.document.fields.length<=12&&e.document.fields.every(f=>typeof f.label==='string'&&f.label.length<=100&&typeof f.value==='string'&&f.value.length<=500)&&(Array.isArray(e.lines)&&e.lines.length===0||rows(e.lines))))&&a.conceptCheck&&typeof a.conceptCheck.prompt==='string'&&a.conceptCheck.prompt.length<=400&&Array.isArray(a.conceptCheck.options)&&a.conceptCheck.options.length===3&&a.conceptCheck.options.every(x=>typeof x==='string'&&x.length<=400)&&[0,1,2].includes(a.conceptCheck.correct)&&typeof a.conceptCheck.feedback==='string'&&a.conceptCheck.feedback.length<=1000;
}
function generatedIssues(a){const issues=[],b=a.blueprint;if(!b)return ['Missing blueprint'];if(!Array.isArray(a.source)||a.source.some(x=>!x||typeof x.evidence!=='string'||!a.notes.includes(x.evidence)))issues.push('Course citations must quote the notes exactly');if(!Array.isArray(a.objectives)||a.objectives.length<1||a.objectives.length>6)issues.push('Use 1–6 objectives');if(!Array.isArray(b.accounts)||b.accounts.length<3||b.accounts.length>24||new Set(b.accounts.map(x=>x.name)).size!==b.accounts.length)issues.push('Chart of accounts must have 3–24 unique accounts');if(!b.accounts?.some(x=>x.name==='Cash'))issues.push('Cash account missing');const names=b.accounts?.map(x=>x.name)||[];const inspectRows=(rows,label)=>{if(Array.isArray(rows)&&rows.length===0)return;if(!Array.isArray(rows)||rows.length<2||rows.length>8){issues.push(label+' needs 2–8 lines for a transaction');return;}if(rows.some(x=>!names.includes(x.account)))issues.push(label+' uses an account outside the chart');if(rows.some(x=>typeof x.debit!=='number'||typeof x.credit!=='number'||x.debit<0||x.credit<0||((x.debit>0)===(x.credit>0))))issues.push(label+' needs one positive side per line');if(Math.abs(rows.reduce((n,x)=>n+x.debit-x.credit,0))>.005)issues.push(label+' does not balance');};if(b.opening?.length)inspectRows(b.opening,'Opening balances');if(!Array.isArray(b.paths)||b.paths.length!==3)issues.push('Exactly three plans required');for(const [i,p]of (b.paths||[]).entries()){if(p.id!==String(i))issues.push('Plan IDs must be ordered 0,1,2');if(!Array.isArray(p.events)||p.events.length<2||p.events.length>18)issues.push('Each plan needs 2–18 records');if(!p.events?.some(e=>e.stage===0)||!p.events?.some(e=>e.stage===finalStage(a)))issues.push('Each plan needs setup and period-end records');for(const e of p.events||[]){if(e.date<day(a,1)||e.date>finalDate(a))issues.push('Record date outside selected month');if(!Array.isArray(e.document?.fields)||e.document.fields.length<3||e.document.fields.length>12)issues.push('Records need 3–12 source facts');inspectRows(e.lines,'Expected entry');}}return [...new Set(issues)].slice(0,6).length?[...new Set(issues)].slice(0,6):['A field exceeded the assignment format or monetary limits'];}
function generatedBalances(scenario,entries){const b=Object.fromEntries(scenario.accountList.map(x=>[x,0]));for(const x of scenario.openingBalances||[])b[x.account]+=x.debit-x.credit;for(const e of Object.values(entries))for(const x of e.rows)b[x.account]+=Number(x.debit||0)-Number(x.credit||0);return Object.fromEntries(Object.entries(b).map(([k,v])=>[k,cents(v)]));}
// Resolve business identity once for every view and source-record field.
function neutralizeBusinessText(text){return String(text??'').replace(/\byour\s+(?:coffee\s*(?:shop|company|business)|cleaning\s*(?:company|business|service)|bakery|design studio|bike repair (?:shop|business)|plant shop|pet grooming (?:business|salon)|photography studio|fitness studio|bookshop)\b/gi,'{{business}}').replace(/\b(?:coffee\s*(?:shop|company|business)|cleaning\s*(?:company|business|service)|bakery|design studio|bike repair shop|plant shop|pet grooming salon|photography studio|fitness studio|bookshop)\b/gi,'{{type}}').replace(/\b(?:cleaning supplies|coffee beans and cups|coffee beans, cups, and filters)\b/gi,'{{supplies}}');}
function enableSimulation(original){if(original?.version!==3||!original.interactive||original.simulation)return original;const a=structuredClone(original),name=a.blueprint.accounts.find(x=>x.type==='revenue')?.name||'Sales Revenue';a.simulation={version:1,revenueAccount:name};if(!a.blueprint.accounts.some(x=>x.name===name))a.blueprint.accounts.push({name,type:'revenue'});return a;}
function withBusinessActivity(original){if(!original||original.publicRun||original.assignment?.simulation||original.assignment?.version!==3||!original.assignment?.interactive)return original;const r=structuredClone(original);r.assignment=enableSimulation(r.assignment);r.scenario=expected(r.assignment,r.choice,r.business);return r;}
function syncBusinessEntries(r){if(!r||r.publicRun)return r;for(const e of availableEvents(r).filter(e=>e.autoPosted)){r.entries[e.id]={date:e.date,rows:structuredClone(e.lines)};}return r;}
function personalize(text,business={name:'Your business',type:'business'}){const name=business.name||'Your business',type=business.type?.toLowerCase()||'business',specialty=business.specialty||business.type||'products and services';return neutralizeBusinessText(String(text??'').replaceAll(name,'{{business}}')).replace(/\{\{\s*(?:business(?:[._ ]name)?|company(?:[._ ]name)?|student_business(?:_name)?)\s*\}\}|\[(?:your |student.?s? )?(?:business|company)(?: name)?\]/gi,()=>name).replace(/\{\{\s*(?:type|business_type)\s*\}\}/gi,()=>type).replace(/\{\{\s*(supplies|order|customer)\s*\}\}/gi,(_,key)=>key==='supplies'?D.catalog({category:'supplies'},business).map(x=>x.name).join(', '):businesses[business.type]?.[key]||'customer orders').replace(/\{\{\s*specialty\s*\}\}/gi,()=>specialty).replace(/\b(?:your (?:business|company)|(?:example|sample) (?:business|company|coffee))\b/gi,()=>name);}
function personalizeDocument(doc,business){const d={...doc,issuer:personalize(doc.issuer,business),status:personalize(doc.status,business),fields:doc.fields.map(f=>({label:personalize(f.label,business),value:/^(?:business|company|business name|company name|student business)$/i.test(f.label.trim())?business.name:personalize(f.value,business)}))};if(!d.fields.some(f=>/^(?:business|company|business name|company name|student business)$/i.test(f.label.trim())))d.fields.unshift({label:'Business',value:business.name});return d;}
function generatedScenario(a,choice,business={name:'Your business',type:'Coffee shop'}){if(a.interactive){const s=generatedScenario(D.materialize(a,choice,business),{plan:0},business);s.decisions=a.interactive.controls.map(c=>personalize(c.label,business)+': '+(c.kind==='basket'?D.catalog(c,business).filter(x=>choice[c.id][x.id]>0).map(x=>choice[c.id][x.id]+' × '+x.name).join(', '):c.kind==='money'?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(choice[c.id]):String(choice[c.id])+(c.kind==='percent'?'%':'')));s.decision=s.decisions.join('; ');return s;}if(!checkAssignment(a)||!Number.isInteger(choice.plan)||choice.plan<0||choice.plan>2)throw Error('Choose a valid operating plan.');const path=a.blueprint.paths[choice.plan],replace=x=>personalize(x,business),events=path.events.map(e=>({...structuredClone(e),document:personalizeDocument(e.document,business),title:replace(e.title),kind:'generated',amount:cents(e.lines.reduce((sum,x)=>sum+x.debit,0)),detail:{document:personalizeDocument(e.document,business)}})).sort((x,y)=>x.stage-y.stage||x.date.localeCompare(y.date)),openingBalances=a.blueprint.opening,s={accountList:a.blueprint.accounts.map(x=>x.name),accountDefinitions:a.blueprint.accounts,openingBalances,opening:cents(openingBalances.filter(x=>x.account==='Cash').reduce((n,x)=>n+x.debit-x.credit,0)),events,operations:a.operations||[],decision:replace(path.description),decisions:[replace(path.label)],stages:(a.periodMonths||1)>1?Array.from({length:a.periodMonths},(_,i)=>{const label=new Date(Date.UTC(a.year,a.month+i-1,1)).toLocaleDateString('en-US',{month:'long',timeZone:'UTC'});return [label+' records',label+' month-end'];}).flat():['Make the arrangements','Run the business','Review the period'],prediction:{...a.conceptCheck,prompt:replace(a.conceptCheck.prompt),options:a.conceptCheck.options.map(replace),feedback:replace(a.conceptCheck.feedback)},effects:[]};const entries=Object.fromEntries(events.map(e=>[e.id,{rows:e.lines}])),b=generatedBalances(s,entries),sum=type=>cents(a.blueprint.accounts.filter(x=>x.type===type).reduce((n,x)=>n+b[x.name],0)),profit=cents(-sum('revenue')-sum('expense'));
 s.effects=a.report==='statements'?[{key:'cash',label:'Ending cash',value:b.Cash},{key:'revenue',label:'Total revenue',value:-sum('revenue')},{key:'expense',label:'Total expenses',value:sum('expense')},{key:'profit',label:'Net income (loss)',value:profit},{key:'assets',label:'Total assets',value:cents(sum('asset')+sum('contraasset'))},{key:'liabilities',label:'Total liabilities',value:-sum('liability')},{key:'equity',label:'Ending equity',value:cents(-sum('equity')-sum('contraequity')+profit)}]:a.blueprint.accounts.filter(x=>events.some(e=>e.lines.some(l=>l.account===x.name))).map((x,i)=>({key:'account_'+i,label:x.name+' · ending '+(['liability','equity','revenue','contraasset'].includes(x.type)?'credit':'debit')+' balance',value:cents(b[x.name]*(['liability','equity','revenue','contraasset'].includes(x.type)?-1:1))}));return s;
}

const api={enableSimulation,withBusinessActivity,neutralizeBusinessText,syncBusinessEntries,pendingDecision,decisionControls,pendingMonth,finalStage,finalDate,personalize,personalizeDocument,decisions:D,generatedIssues,validGenerated,generatedScenario,topic,businesses,colors,styles,districts,normalizeBusiness,concepts,analyzeNotes,generateAssignment,episodeChoices,defaultEpisodeChoice,validEpisodeChoice,availableEvents,topics,accounts,checkAssignment,suggestTopic,expected,validateRows,assess,balances,grade,day,end};if(typeof module!=='undefined')module.exports=api;else root.Lessons=api;
})(globalThis);
