const {test}=require('node:test'),assert=require('node:assert/strict'),L=require('./lesson-engine');
function a(topic){return {version:1,id:'test-'+topic,title:'Test lesson',topic,instructions:'Practice the topic',course:'Intro',year:2026,month:9,support:'guided',notes:''};}
function journal(s){return Object.fromEntries(s.events.map(e=>[e.id,{date:e.date,rows:[{account:e.debit,debit:e.amount,credit:0},{account:e.credit,debit:0,credit:e.amount}]}]));}
test('rent choices change future benefits without changing the lesson objective',()=>{const one=L.expected(a('prepaid'),{location:1,months:1}),six=L.expected(a('prepaid'),{location:1,months:6});assert.equal(one.events[0].amount,250);assert.equal(six.events[0].amount,1500);assert.equal(one.events[1].amount,six.events[1].amount);assert.equal(L.balances(six,journal(six))['Prepaid Rent'],1250);});
test('receivable collection does not earn revenue twice',()=>{const s=L.expected(a('receivables'),{order:2,collection:1}),b=L.balances(s,journal(s));assert.equal(b['Sales Revenue'],-1000);assert.equal(b['Accounts Receivable'],500);assert.equal(b.Cash,8500);});
test('depreciation is noncash and uses selected useful life',()=>{const s=L.expected(a('equipment'),{level:2,life:1}),b=L.balances(s,journal(s));assert.equal(s.events[1].amount,30);assert.equal(b.Cash,6200);assert.equal(b['Accumulated Depreciation'],-30);});
test('episodes reset their balances instead of carrying earlier work',()=>{const x=L.expected(a('capital'),{investment:0,ad:2}),y=L.expected(a('prepaid'),{location:0,months:3});assert.equal(L.balances(x,journal(x)).Cash,2800);assert.equal(y.opening,8000);assert.equal(L.balances(y,{}).Cash,8000);});
test('assessment separates date, account choice, amounts and corrections',()=>{const s=L.expected(a('prepaid'),{location:0,months:3}),e=s.events[0],rows=journal(s)[e.id].rows;assert.equal(L.assess(rows,'2026-09-02',e).date,false);assert.equal(L.assess(rows,e.date,e).correct,true);const wrong=[{account:'Rent Expense',debit:450,credit:0},{account:'Cash',debit:0,credit:450}];assert.equal(L.validateRows(wrong),null);assert.equal(L.assess(wrong,e.date,e).account,false);const run={scenario:s,first:{payment:L.assess(wrong,e.date,e),adjustment:L.assess(journal(s).adjustment.rows,s.events[1].date,s.events[1])},predictionFirst:0,effectsFirst:{expense:150,remaining:300,cash:7550}};assert.equal(L.grade(run).journal,53);assert.equal(L.grade(run).effects,15);});
test('imports reject unsupported topics, dates and oversized material',()=>{assert.equal(L.checkAssignment(a('prepaid')),true);assert.equal(L.checkAssignment({...a('prepaid'),month:13}),false);assert.equal(L.checkAssignment({...a('prepaid'),topic:'made-up'}),false);assert.equal(L.checkAssignment({...a('prepaid'),topic:'constructor'}),false);assert.equal(L.checkAssignment({...a('prepaid'),id:''}),false);assert.equal(L.checkAssignment({...a('prepaid'),notes:'x'.repeat(30001)}),false);});
