const guidedRender=render;
function startupComplete(){return ['Rent Expense','Equipment','Supplies','Advertising Expense'].every(a=>state.ledger.some(e=>e.event.debit===a&&!e.event.correction));}
function monthFinished(){return !!state.monthReports?.some(r=>r.period===periodInfo().number);}
render=function(){guidedRender();if(!state)return;const p=periodInfo(),finished=monthFinished();$('.intro p').textContent=`Month ${p.number} · ${finished?'Review your results and close the books':'Prepare your business, then open for customers'}`;
if(view==='business'){
$('.mission').hidden=true;$('.more-decisions').hidden=true;const next=$('.next-step');let title,body;if(state.pending){title=state.pending.credit==='Owner Capital'?'Record your starting investment':finished?'Record the next item from your monthly report':'Record your startup purchase';body=state.pending.credit==='Owner Capital'?'Your business begins with $5,000 from you, the owner. The desk walks you through your first entry.':'Read the event at the desk. Enter the accounts and amounts, then post. Finish this entry before moving on.';}else if(finished){title='Your month is complete. Prepare the financial statements.';body='Review your monthly report and general ledger. Use Period financials to prepare the statements, explain your results, and begin the next month.';}else if(!startupComplete()){title='Set up your business before opening';body='Complete the four startup steps below. Each payment creates a journal entry. Choose reasonable budgets so you have cash left to operate.';}else{title='You’re ready to open for customers';body='You can buy more supplies, improve equipment, or adjust your advertising. When ready, open for the month. Customer activity is generated from your resources, advertising, and market conditions.';}next.querySelector('h3').textContent=title;next.querySelector('p').textContent=body;
const first=!state.monthReports?.length;const steps=[['rent','1. Rent your space','Rent Expense','Pay for the first month’s workspace. Future rent repeats automatically.'],['equipment','2. Equip your business','Equipment','Buy equipment to increase the amount of work you can handle.'],['supplies','3. Stock your supplies','Supplies','Customers use supplies. Running out limits how much you can sell.'],['advertise','4. Tell people you’re open','Advertising Expense','Advertising attracts inquiries; it does not guarantee sales.']];const cards=$('.cards');cards.innerHTML=first&&!startupComplete()?steps.map(([id,label,a,description])=>{const done=state.ledger.some(e=>e.event.debit===a&&!e.event.correction);const earlier=steps.slice(0,steps.findIndex(t=>t[0]===id)).every(t=>state.ledger.some(e=>e.event.debit===t[2]&&!e.event.correction));return `<button class="choice" data-setup="${id}" ${state.pending||done||!earlier?'disabled':''}>${done?'✓ ':''}${label}<small>${done?'Completed — transaction recorded':description}</small></button>`;}).join(''):!finished?[['supplies','Restock supplies','Purchase what you need for this month.'],['equipment','Improve equipment','Expand service capacity.'],['advertise','Run an advertising campaign','Choose your advertising budget.']].map(([id,label,desc])=>`<button class="choice" data-setup="${id}" ${state.pending?'disabled':''}>${label}<small>${desc}</small></button>`).join(''):'';
cards.querySelectorAll('[data-setup]').forEach(b=>b.onclick=()=>choose(b.dataset.setup));const old=$('#operate-month');if(old)old.remove();if(!finished){const run=document.createElement('button');run.id='operate-month';run.textContent=first?'Open for your first month →':'Open for this month →';run.disabled=!!state.pending||!startupComplete();run.onclick=operateMonth;cards.after(run);}const instructions=$('.layout .card>p');instructions.textContent=first?'Set up a real operating plan. You choose budgets; customers arrive when you open.':'Prepare for the next month. Rent repeats automatically, equipment carries forward, and unused supplies remain on hand.';$('.layout .card>.foot').textContent='Sales depend on customer demand, advertising, equipment capacity, and available supplies. You do not choose the sales amount.';if(finished){const report=state.monthReports.find(r=>r.period===p.number);const panel=document.createElement('section');panel.className='card monthly-report';panel.innerHTML=`<div class="tag">MONTH ${p.number} · OPERATIONS REPORT</div><h2>Here’s what happened.</h2><p>${esc(report.conditions)}. Your advertising brought customer inquiries; your equipment and supplies limited the work you could complete.</p><div class="report-grid"><div><span>Services delivered</span><strong>${money(report.sales)}</strong></div><div><span>Customers paid cash</span><strong>${money(report.cashSales)}</strong></div><div><span>Customers will pay later</span><strong>${money(report.creditSales)}</strong></div><div><span>Supplies used</span><strong>${money(report.used)}</strong></div><div><span>Old balances collected</span><strong>${money(report.collected)}</strong></div><div><span>Recurring rent paid</span><strong>${money(report.rent)}</strong></div></div><p class="foot">Startup and preparation purchases appear separately in your journal. This report describes business activity; it is not a completed financial statement.</p></section>`;$('.layout').after(panel);}}
if(view==='financials'){const msg=$('.workspace>.message');if(msg&&!finished)msg.textContent='Open your business for the month and record its activity before submitting financial statements. You may draft them now.';$('.page-heading .tag').textContent=`MONTH ${p.number} CLOSE · FINANCIAL STATEMENTS`;}
};
function operateMonth(){if(state.pending||!startupComplete()||monthFinished())return;const p=periodInfo(),market=marketEvent();const rent=p.number>1?(state.monthlyRent||300):0;if(Math.max(0,rent-(state.prepaidActual||0))>state.cash){message='You need enough cash for recurring rent before opening. Your customers still owe '+money(state.receivable)+'. Use the collection option below to collect an existing balance.';render();const b=document.createElement('button');b.textContent='Collect an outstanding payment';b.disabled=state.receivable<=0;b.onclick=()=>choose('collect');$('.cards').append(b);return;}
const capacity=500+state.equipment;const demand=Math.round(marketDemand()*(1+Math.min(state.adBudget||0,1000)/1000));const sales=Math.max(0,Math.floor(Math.min(capacity,demand,state.supplies/supplyRate())));const creditSales=Math.round(sales*.3);const cashSales=sales-creditSales;const used=Math.round(sales*supplyRate()*100)/100;const collected=Math.round(state.receivable*.6*100)/100;const events=[];const add=(title,text,amount,debit,credit)=>{if(amount>0)events.push({title,text,amount,debit,credit,reason:'Generated from monthly operations'});};
add('Monthly rent',`The business paid ${money(rent)} cash for this month’s rent.`,rent,'Rent Expense','Cash');add('Customer payments collected',`Customers paid ${money(collected)} of balances from prior months. This was not new revenue.`,collected,'Cash','Accounts Receivable');add('Monthly cash sales',`The business delivered services and received ${money(cashSales)} cash this month.`,cashSales,'Cash','Sales Revenue');add('Monthly credit sales',`The business delivered ${money(creditSales)} of services this month. These customers will pay in a later month.`,creditSales,'Accounts Receivable','Sales Revenue');add('Monthly supplies used',`The business used ${money(used)} of supplies to deliver this month’s services.`,used,'Supplies Expense','Supplies');state.cash+=cashSales+collected-rent;state.receivable+=creditSales-collected;state.supplies=Math.round((state.supplies-used)*100)/100;state.adBudget=0;state.monthReports||=[];state.monthReports.push({period:p.number,conditions:market.name,sales,cashSales,creditSales,used,collected,rent});state.decisions=p.startDecisions+10;state.day++;state.pending=events.shift()||null;state.corrections.push(...events);message=sales?'Your monthly report is ready. Record each event at the desk.':'No sales this month: check your supplies before opening next month. Record any recurring expenses.';hint=false;rows=[{account:'',debit:'',credit:''},{account:'',debit:'',credit:''}];save();render();}
const oldHelp=showHelp;
showHelp=function(){oldHelp();$('#modal h2').textContent='Set up. Open. Keep the books.';$('#modal .instructions').innerHTML='<li><strong>Set up your business.</strong><p>Record your owner investment, then pay rent, buy equipment and supplies, and advertise. Choose the budgets and record each transaction.</p></li><li><strong>Open for the month.</strong><p>Customers arrive based on your preparation and the market. A monthly report summarizes cash sales, credit sales, supplies used, rent, and collections. Write the journal entries for each event.</p></li><li><strong>Close the month.</strong><p>Use the general ledger to prepare the financial statements. Explain your results, then restock and plan the next month.</p></li>';};
render();

if($('#modal')?.open)showHelp();
