const quarterPeriods=[9,10,11,12];
function quarterNumber(){return quarterPeriods.indexOf(periodInfo().number)+1;}
function quarterStart(){return periodInfo().number;}
function quarterLabel(){return monthName(periodInfo().number);}
const dailyDate=transactionDate;
transactionDate=function(period,end=false){const q=quarterPeriods.indexOf(period);if(q<0)return dailyDate(period,end);const month=quarterPeriods[q];const day=end?new Date(2026,month,0).getDate():Math.min(25,1+(state?.documents?.filter(d=>d.month===period).length||0)*2);return `2026-${String(month).padStart(2,'0')}-${String(day).padStart(2,'0')}`;};
const datePost=post;
post=function(){const d=state.pending;if(!d)return;const date=$('#journal-date')?.value||state.journalDate||'';if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||Number.isNaN(Date.parse(date))){message='Enter a valid journal-entry date.';render();return;}if(date!==(d.date||transactionDate(d.month||periodInfo().number))){message='Check the transaction date on the source document.';state.journalDate=date;render();return;}const before=state.ledger.length;datePost();if(state.ledger.length>before){state.ledger.at(-1).entryDate=date;state.journalDate='';save();}};
operateMonth=function(){if(state.completed||monthFinished()||!startupComplete())return;const q=quarterNumber(),period=periodInfo().number,date=transactionDate(period,true),rate=state.monthlyRent||150,initial=q===1?state.documents.filter(d=>d.debit==='Rent Expense'&&d.credit==='Cash').reduce((n,d)=>n+d.amount,0):0,rent=Math.max(0,rate-initial),prepaid=Math.min(state.prepaidActual||0,rent),cashRent=rent-prepaid,payable=state.tradePayable||0;if(cashRent+payable>state.cash){message=`You need ${money(cashRent+payable)} for rent and supplier payments. Raise capital before opening.`;render();return;}
const add=(title,amount,debit,credit,extra={})=>{if(amount>0)addDocument({title,amount:Math.round(amount*100)/100,debit,credit,date,...extra});};state.cash-=cashRent+payable;state.prepaidActual=Math.round(((state.prepaidActual||0)-prepaid)*100)/100;add('Monthly rent payment',cashRent,'Rent Expense','Cash',{coverageStart:quarterStart(),coverageMonths:1});add('Prepaid rent coverage used',prepaid,'Rent Expense','Prepaid Rent',{coverageStart:quarterStart(),coverageMonths:prepaid/rate,monthlyRate:rate});if(payable){add('Payment of supplier invoice',payable,'Accounts Payable','Cash',{date:'2026-11-15'});state.tradePayable=0;}
if(q===2){state.supplies+=120;state.tradePayable=120;add('Supplies delivered on account',120,'Supplies','Accounts Payable',{itemDescription:businessProfiles[state.type].supplies,paymentDue:'2026-11-15'});}
const demand=Math.round(marketDemand()*(1+Math.min(state.adBudget||0,1000)/1000)),capacity=500+state.equipment,sales=Math.floor(Math.min(demand,capacity,state.supplies/supplyRate())),share=[.3,.5,.2,.35][q-1],credit=Math.round(sales*share),cash=sales-credit,used=Math.round(sales*supplyRate()*100)/100,collected=Math.round(state.receivable*([0,.45,.8,.9][q-1])*100)/100;state.cash+=cash+collected;state.receivable+=credit-collected;state.supplies=Math.round((state.supplies-used)*100)/100;add('Monthly customer payments collected',collected,'Cash','Accounts Receivable');add('Monthly cash sales',cash,'Cash','Sales Revenue');add('Monthly customer invoices',credit,'Accounts Receivable','Sales Revenue');add('Monthly stock usage',used,'Supplies Expense','Supplies');
if(q===3){state.cash+=180;state.customerAdvance=180;add('Customer deposit for future services',180,'Cash','Unearned Revenue',{serviceDate:'2026-12-20'});}const advanceEarned=q===4?(state.customerAdvance||0):0;if(q===4){if(state.customerAdvance){add('Prepaid customer order fulfilled',state.customerAdvance,'Unearned Revenue','Sales Revenue',{date:'2026-12-20'});state.customerAdvance=0;}state.wagesOwed=90;add('Year-end staff wages earned, unpaid',90,'Wages Expense','Wages Payable',{paymentDue:'2027-01-10'});}
state.adBudget=0;state.monthReports||=[];state.monthReports.push({period,conditions:marketEvent().name,sales,cashSales:cash,creditSales:credit,used,collected,rent:cashRent,prepaidUsed:prepaid,advanceEarned});state.decisions=periodInfo().startDecisions+10;message='Monthly records are ready. Enter dated records, reconcile the bank, then prepare financial statements.';save();render();};
const quarterRender=render;
render=function(){if(state&&state.cadence!=='september-monthly'){if(!state.documents?.length&&!state.monthReports?.length){state.cadence='september-monthly';state.period={number:9,startDecisions:0,beginning:{ledger:[],effectiveCount:0}};save();}else{renderLegacyNotice();return;}}quarterRender();if(!state){$('.welcome p').textContent='Open your business on September 1 and run it through December. Interpret dated documents, keep the books, and finish with annual financial statements and an audit.';return;}const q=quarterNumber();$('.intro p').textContent=quarterLabel();$('.year-progress strong').textContent=state.completed?'Year complete':`Month ${q} of 4 · ${monthName(periodInfo().number)}`;$('.year-progress i').style.width=q/4*100+'%';$('.year-progress small').textContent='Operate → enter dated records → reconcile → prepare statements. Finish with year-end adjustments, closing entries and an audit.';
if(view==='business'){const pending=state.pending;if(pending){const desk=$('.layout').children[1],label=document.createElement('label');label.className='field';label.innerHTML=`Journal-entry date<input id="journal-date" aria-label="Journal-entry date" type="date" value="${esc(state.journalDate||'')}" required><small>Use the date shown on the document.</small>`;desk.querySelector('table').before(label);$('#journal-date').oninput=e=>state.journalDate=e.target.value;$('#post').onclick=post;}
const reportTag=$('.monthly-report .tag');if(reportTag)reportTag.textContent=quarterLabel()+' · OPERATIONS REPORT';const run=$('#operate-month');if(run)run.textContent='Open for this month →';const missing=state.documents.filter(d=>!d.posted).length,rec=!!state.bankRecs?.[periodInfo().number],report=state.reports?.find(r=>r.period===periodInfo().number),path=document.createElement('section');path.className='card quarter-path';path.innerHTML=`<div class="tag">HOW TO MOVE TO THE NEXT MONTH</div><h3>${quarterLabel()}</h3><ol><li>${monthFinished()?'✓':'○'} Open for the month</li><li>${missing?'○':'✓'} Enter records (${missing} remaining)</li><li>${rec?'✓':'○'} Reconcile the bank</li><li>${report?.correct===report?.total&&report?'✓':'○'} Submit financial statements</li></ol><button id="quarter-next-step">${!monthFinished()?'View business setup':missing?'View unposted records':!rec?'Reconcile the bank':'Prepare financial statements →'}</button>`;$('.layout').before(path);$('#quarter-next-step').onclick=()=>{if(!monthFinished())$('.cards').scrollIntoView({behavior:'smooth'});else if(missing)$('.record-inbox').scrollIntoView({behavior:'smooth'});else{view=rec?'financials':'bank';render();}};decorateQuarter();const opsReport=state.monthReports?.find(r=>r.period===periodInfo().number);if(opsReport?.advanceEarned){const grid=$('.report-grid');if(grid){const item=document.createElement('div');item.innerHTML='<span>Previously prepaid services completed</span><strong>'+money(opsReport.advanceEarned)+'</strong>';grid.append(item);}}}
if(view==='financials'){$('.page-heading .tag').textContent=q===4?'YEAR-END FINANCIAL STATEMENTS':quarterLabel();$('.page-heading h2').textContent=q===4?'Prepare annual financial statements':'Prepare monthly financial statements';const form=$('#financial-form'),handler=form.onsubmit;form.onsubmit=e=>{handler(e);const next=$('#next-period');if(next&&q<4){next.textContent=`Start ${monthName(quarterPeriods[q])} →`;next.onclick=()=>{state.period={number:quarterPeriods[q],startDecisions:state.decisions||0,beginning:{ledger:structuredClone(state.ledger),effectiveCount:Engine.effective(state.ledger).length}};state.draftFinancials={};state.pending=null;state.journalDate='';view='business';save();render();window.scrollTo({top:0,behavior:'smooth'});};}};}
const walker=document.createTreeWalker($('#app'),NodeFilter.SHOW_TEXT),nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const node of nodes)if(!node.parentElement.closest('.source-document,script,style,input,select'))node.textContent=node.textContent.replace(/Open for the month/g,'Open for the month').replace(/next month/g,'next month').replace(/twelve months/g,'September through December');};
function decorateQuarter(){const svg=$('.storefront');if(!svg)return;const q=quarterNumber();svg.querySelector('#sky stop')?.setAttribute('stop-color',['#dcebe4','#e4edcf','#e8d9bd','#dce3ef'][q-1]);const scene=document.createElement('div');scene.className='scene-update';scene.innerHTML=`<strong>${['Opening season','Settling into the neighborhood','Growing customer relationships','Year-end in the neighborhood'][q-1]}</strong><span>${esc(state.equipmentLevel||'Preparing the space')} · ${esc(state.location?.name||'Choose your location')}</span>`;$('.town').append(scene);if(q>1){const group=document.createElementNS('http://www.w3.org/2000/svg','g');group.innerHTML=q===2?'<rect x="228" y="247" width="75" height="23" fill="#f5e1ab"/><text x="266" y="263" text-anchor="middle" font-size="9" fill="#496343">NOW OPEN</text>':q===3?'<rect x="210" y="267" width="28" height="22" fill="#a78762"/><circle cx="224" cy="255" r="20" fill="#688348"/><rect x="518" y="267" width="27" height="22" fill="#a78762"/><circle cx="531" cy="255" r="20" fill="#688348"/>':'<path d="M213 145 Q380 180 548 145" fill="none" stroke="#657950" stroke-width="4"/><g fill="#d9b15b"><circle cx="245" cy="152" r="4"/><circle cx="310" cy="161" r="4"/><circle cx="380" cy="166" r="4"/><circle cx="450" cy="161" r="4"/><circle cx="515" cy="152" r="4"/></g>';svg.append(group);}}
function renderLegacyNotice(){$('#app').innerHTML=`<main class="shell">${header()}<section class="welcome"><h1>Four months. A clearer start.</h1><p>Your previous business is saved. The new version runs September through December. Download your existing progress, then start a new business to try it.</p><button id="legacy-download">Download existing progress</button><button class="secondary" id="fresh-quarter">Start September business</button></section></main>`;$('#legacy-download').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='monthly-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};$('#fresh-quarter').onclick=()=>{localStorage.setItem('ledger-lane-monthly-backup',JSON.stringify(state));state=null;localStorage.removeItem('ledger-lane-intro');localStorage.removeItem('ledger-lane');render();};}
const oldQuarterSource=sourceDocument;
sourceDocument=function(d){let html=oldQuarterSource(d);if(d.credit==='Accounts Payable')html=paperOverride(d,'Supplier invoice','Market Street Supply Co.','UNPAID',`Delivered: ${esc(d.date)}<br>Goods: ${esc(d.itemDescription)}<br>Invoice due: ${esc(d.paymentDue)}<br>Payment received: $0.00`);if(d.debit==='Accounts Payable')html=paperOverride(d,'Bank payment confirmation','Neighborhood Bank','PAID','Recipient: Market Street Supply Co.<br>Reference: settlement of the prior supplier invoice');if(d.credit==='Unearned Revenue')html=paperOverride(d,'Customer advance receipt',state.name,'RECEIVED',`Funds received before service delivery.<br>Service scheduled for: ${esc(d.serviceDate)}<br>Service delivered on receipt date: no`);if(d.debit==='Unearned Revenue')html=paperOverride(d,'Service completion confirmation',state.name,'COMPLETED',`Order fulfilled: ${esc(d.date)}<br>Previously received deposit applied to completed services.<br>New cash collected: $0.00`);if(d.credit==='Wages Payable')html=paperOverride(d,'Payroll accrual schedule',state.name,'UNPAID',`Work completed by: ${esc(d.date)}<br>Unpaid wages: ${money(d.amount)}<br>Scheduled pay date: ${esc(d.paymentDue)}`);if(d.coverageStart)html=html.replace(/Coverage: [\s\S]*?<br>/,`Coverage begins: ${monthName(d.coverageStart)}; ${d.coverageMonths} month${d.coverageMonths===1?'':'s'}<br>`).replace(/Coverage month: [\s\S]*?<br>/,`Coverage used: ${d.coverageMonths} month${d.coverageMonths===1?'':'s'} starting ${monthName(d.coverageStart)}<br>`).replace('Coverage consumed: one month','Monthly rate: '+money(state.monthlyRent));if(d.debit==='Prepaid Rent')html=html.replace(/Coverage: [\s\S]*?<br>/,`Coverage begins: ${monthName(Number(d.date.slice(5,7)))}; ${d.coverageMonths} months in advance<br>`);if(d.debit==='Advertising Expense'){const aq=quarterPeriods.indexOf(d.month)+1;html=html.replace(/Campaign period: [^<]+/,`Campaign period: ${monthName(d.month)}`).replace('Campaign delivered during the current month.','Campaign delivered during the month.');}if(d.title.startsWith('Monthly')){const dq=quarterPeriods.indexOf(d.month)+1,label=monthName(d.month);html=html.replace(/Reporting period: [\s\S]*?<br>/,`Reporting period: ${label}<br>`).replace(/Services delivered during [^<]+/,'Services delivered during '+label).replace('Daily sales summary','Monthly sales report');if(d.debit==='Accounts Receivable'){const issuedMonth=Number(d.date.slice(5,7));const due=new Date(Date.UTC(2026,issuedMonth,15)).toISOString().slice(0,10);html=html.replace(/Due date: [^<]+/,'Due date: '+due);}}return html;};
function paperOverride(d,title,issuer,status,detail){return `<article class="source-document"><div class="paper-top"><span>${esc(issuer)}</span><span class="paper-status">${status}</span></div><h2>${title}</h2><div class="paper-meta"><span>Document ${esc(d.docId)}</span><span>${esc(d.date)}</span></div><div class="paper-party">${esc(state.name)}</div><div class="paper-item">${esc(d.title)}</div><p>${detail}</p><div class="paper-total"><span>Total</span><strong>${money(d.amount)}</strong></div><div class="paper-footer">Business copy · Retain with company records</div></article>`;}
const oldKind=documentKind;
documentKind=function(d){if(d.credit==='Accounts Payable')return 'Supplier invoice';if(d.debit==='Accounts Payable')return 'Bank payment confirmation';if(d.credit==='Unearned Revenue')return 'Customer advance receipt';if(d.debit==='Unearned Revenue')return 'Service completion confirmation';if(d.credit==='Wages Payable')return 'Payroll accrual schedule';return oldKind(d);};
render();
// Bank timing is based on dated documents, independently of student postings.
bankData=function(){const period=periodInfo().number,end=transactionDate(period,true);let running=0,outstanding=0,lines=[];for(const d of state.documents.filter(d=>d.month<=period)){const change=d.debit==='Cash'?d.amount:d.credit==='Cash'?-d.amount:0;if(!change)continue;const uncleared=change<0&&d.date===end&&['Rent Expense','Accounts Payable'].includes(d.debit);if(uncleared){outstanding+=d.amount;continue;}running+=change;lines.push({title:d.title,month:d.month,date:d.date,change,balance:Math.round(running*100)/100});}return {balance:Math.round(running*100)/100,outstanding:Math.round(outstanding*100)/100,lines,book:Engine.balances(state.ledger).Cash};};
const monthlyTour=introTour;
introTour=function(index=0){monthlyTour(index);const dialog=$('#tour-dialog');dialog.querySelectorAll('p,div,h2,li').forEach(el=>{if(!el.children.length)el.textContent=el.textContent.replace('January through December','September through December').replace('prepare monthly financial statements','prepare monthly financial statements').replace('monthly statements','monthly statements').replace('Finish the month and the year','Finish each month and the year').replace('In December','At the end of December').replace('12 months','4 months');});};
const periodRender=render;
render=function(){periodRender();if(!state||state.cadence!=='september-monthly')return;if(view==='bank'){const paragraphs=$('.page-heading').querySelectorAll('p');paragraphs.forEach(p=>p.textContent='This bank statement is independent of your journal. Rent payments made on the final day of this month have not yet cleared; they clear during the next month. All other cash movements clear within the month.');$('.reflection p').textContent='Review dated payment records. Subtract month-end rent payments that have not cleared, then compare the adjusted bank balance with Cash in your T account.';}if(view==='business'){$('.next-step p').textContent='Use the monthly checklist below to move forward. Receipts and reports can wait while you operate. After posting them, reconcile Cash and submit your statements to unlock Start next month.';const closing=$('#quarter-next-step');if(state.completed&&closing){closing.disabled=true;closing.textContent='Year complete';}document.querySelectorAll('.journal tr').forEach(tr=>{const entryDate=tr.querySelector('td');if(entryDate)entryDate.textContent=entryDate.textContent.replace('Day / Transaction','Date / Transaction');});}if(view==='financials')$('.page-heading p').textContent=quarterNumber()===4?'Use your adjusted T accounts to prepare statements for September 1–December 31. The balance sheet shows year-end balances. Enter dollars to the cent.':'Use your T accounts to prepare statements for this month. Income and cash flow cover the month; the balance sheet shows cumulative balances. Enter dollars to the cent.';};
render();
function advanceQuarter(){const q=quarterNumber();if(q>=4)return;state.period={number:quarterPeriods[q],startDecisions:state.decisions||0,beginning:{ledger:structuredClone(state.ledger),effectiveCount:Engine.effective(state.ledger).length}};state.draftFinancials={};state.pending=null;state.journalDate='';view='business';save();render();window.scrollTo({top:0,behavior:'smooth'});}
const recordViewer=openRecord;
openRecord=function(d){recordViewer(d);const click=$('#work-record').onclick;$('#work-record').onclick=()=>{state.journalDate='';click();};};
const progressRender=render;
render=function(){progressRender();if(!state||state.cadence!=='september-monthly')return;if(view==='business'&&quarterNumber()<4){const r=state.reports?.find(r=>r.period===periodInfo().number),f=Engine.financials(state.ledger,periodInfo().beginning),ready=monthFinished()&&!state.documents.some(d=>!d.posted)&&state.bankRecs?.[periodInfo().number]&&r?.correct===r?.total&&r?.results.every(x=>Math.abs(x.entered-f[x.key])<.005);if(ready){$('#quarter-next-step').textContent=`Start ${monthName(quarterPeriods[quarterNumber()])} →`;$('#quarter-next-step').onclick=advanceQuarter;}}};
render();
const growthRender=render;
render=function(){growthRender();if(!state||state.cadence!=='september-monthly'||view!=='business')return;const svg=$('.storefront');if(svg&&state.equipment>0){const g=document.createElementNS('http://www.w3.org/2000/svg','g');let icon=state.type==='Coffee shop'?'<rect x="236" y="242" width="52" height="19" rx="2" fill="#63776e"/><rect x="244" y="237" width="10" height="5" fill="#ddd8c1"/><rect x="270" y="237" width="10" height="5" fill="#ddd8c1"/><circle cx="260" cy="249" r="3" fill="#dfc78d"/>':state.type==='Design studio'?'<rect x="239" y="219" width="47" height="33" fill="#456761"/><rect x="243" y="223" width="39" height="25" fill="#bad3c3"/><path d="M262 252V262M249 262H276" stroke="#456761" stroke-width="4"/>':'<circle cx="242" cy="252" r="13" fill="none" stroke="#466559" stroke-width="3"/><circle cx="283" cy="252" r="13" fill="none" stroke="#466559" stroke-width="3"/><path d="M242 252L255 232L270 252H242M255 232L283 252M253 228H263" fill="none" stroke="#466559" stroke-width="3"/>';g.innerHTML=icon;if(state.equipment>=1200){const second=document.createElementNS('http://www.w3.org/2000/svg','g');second.setAttribute('transform','translate(220 0)');second.innerHTML=icon;g.append(second);}svg.append(g);}const date=$('#journal-date');if(date){date.min='2026-09-01';date.max='2026-12-31';}};
render();
