const text=maxLength=>({type:'string',maxLength}),string=text(400),number={type:'number',minimum:0,maximum:1000000},array=(items,minItems=0,maxItems=100)=>({type:'array',items,minItems,maxItems}),object=properties=>({type:'object',properties,required:Object.keys(properties),additionalProperties:false});
const line=object({account:text(60),debit:number,credit:number}),event=object({id:{type:'string',pattern:'^[a-z0-9-]{1,60}$'},title:text(120),date:string,stage:{type:'integer',enum:[0,1,2]},dateControl:{type:'string',enum:['none','decision1','decision2','decision3','decision4','decision5','decision6']},document:object({layout:{type:'string',enum:['invoice','receipt','payment','bank','count','schedule','quote']},issuer:text(120),status:text(50),fields:array(object({label:text(100),value:text(500)}),3,12)}),lines:array(line,0,8)});
export function makeGenerationSchema(paragraphs,year=2026,month=9){
 const days=new Date(Date.UTC(year,month,0)).getUTCDate(),prefix=year+'-'+String(month).padStart(2,'0')+'-';
 const datedEvent={...event,properties:{...event.properties,date:{type:'string',enum:Array.from({length:days},(_,i)=>prefix+String(i+1).padStart(2,'0'))}}};
 return object({title:text(160),instructions:text(10000),objectives:array(string,1,6),source:array(object({paragraph:{type:'integer',enum:paragraphs.map((_,i)=>i)}}),1,6),conceptCheck:object({prompt:string,options:array(string,3,3),correct:{type:'integer',enum:[0,1,2]},feedback:text(1000)}),blueprint:object({accounts:array(object({name:text(60),type:{type:'string',enum:['asset','contraasset','liability','equity','contraequity','revenue','expense']}}),3,24),paths:array(object({id:{type:'string',enum:['0','1','2']},label:text(100),description:text(1200),events:array(datedEvent,4,18)}),3,3)})});
}
export function makeTopicSchema(paragraphs,autoTimeline=false){return object({...(autoTimeline?{timeline:object({startMonth:{type:'integer',minimum:1,maximum:12},months:{type:'integer',minimum:1,maximum:4},reason:text(300)})}:{}),topics:array(object({name:text(80),principle:text(400),method:text(600)}),1,6),sourceParagraphs:array({type:'integer',enum:paragraphs.map((_,i)=>i)},1,6)});}
export function makeInteractiveSchema(year,month,depth='standard',months=1){const dates=[];for(let offset=0;offset<months;offset++){const m=month+offset,days=new Date(Date.UTC(year,m,0)).getUTCDate(),prefix=year+'-'+String(m).padStart(2,'0')+'-';for(let day=1;day<=days;day++)dates.push(prefix+String(day).padStart(2,'0'));}return object({title:text(160),instructions:text(1200),objectives:array(string,1,6),accounts:array(object({name:text(60),type:{type:'string',enum:['asset','contraasset','liability','equity','contraequity','revenue','expense']}}),3,24),controls:array(object({id:{type:'string',enum:['decision1','decision2','decision3','decision4','decision5','decision6']},monthOffset:{type:'integer',enum:Array.from({length:months},(_,i)=>i)},decisionStage:{type:'integer',enum:Array.from({length:months>1?months*2:3},(_,i)=>i)},kind:{type:'string',enum:['basket','money','number','date']},category:{type:'string',enum:['supplies','merchandise','equipment','sales','none']},label:text(120),purpose:text(400),min:number,max:number,step:number,defaultValue:number}),1,6),events:array(object({id:{type:'string',pattern:'^[a-z0-9-]{1,60}$'},title:text(120),date:{type:'string',enum:dates},stage:{type:'integer',enum:[0,1,2]},dateControl:{type:'string',enum:['none','decision1','decision2','decision3','decision4','decision5','decision6']},document:object({layout:{type:'string',enum:['invoice','receipt','payment','bank','count','schedule','quote']},issuer:text(120),status:text(50),fields:array(object({label:text(100),value:text(200)}),3,6)}),lines:array(object({account:text(60),side:{type:'string',enum:['debit','credit']},formula:{type:'string',pattern:'^(?:decision[1-6]|[0-9]+(?:\\.[0-9]+)?|\\.[0-9]+|[<>=+*/() -]){1,100}$'}}),0,8)}),2,depth==='focused'?6:depth==='extended'?14:10)});}
