(function(root){
const topics={prepaid:{name:'Prepaid expenses',goal:'Distinguish paying for future benefits from using those benefits.',effect:'Show rent used this month and rent remaining for future months.'},receivables:{name:'Credit sales & collections',goal:'Separate earning revenue from collecting a customer payment.',effect:'Show revenue earned, cash received, and the customer balance still owed.'},equipment:{name:'Equipment & depreciation',goal:'Separate buying a long-lived asset from allocating its cost over time.',effect:'Show equipment cost, depreciation expense, and net equipment value.'},capital:{name:'Owner investment & cash expenses',goal:'Distinguish owner contributions from revenue and business expenses.',effect:'Show contributed capital, cash remaining, and expenses incurred.'}};
const accounts=['Cash','Accounts Receivable','Prepaid Rent','Equipment','Accumulated Depreciation','Owner Capital','Sales Revenue','Rent Expense','Depreciation Expense','Advertising Expense'];
const cents=n=>Math.round(n*100)/100;
function checkAssignment(a){if(!a||a.version!==1||!Object.hasOwn(topics,a.topic)||typeof a.id!=='string'||!a.id.trim()||a.id.length>100||typeof a.title!=='string'||!a.title.trim()||a.title.length>160||typeof a.instructions!=='string'||a.instructions.length>10000||!Number.isInteger(a.year)||a.year<2020||a.year>2100||!Number.isInteger(a.month)||a.month<1||a.month>12||!['guided','independent'].includes(a.support))return false;return typeof a.course==='string'&&a.course.length<=120&&typeof a.notes==='string'&&a.notes.length<=30000;}
function suggestTopic(notes){const t=notes.toLowerCase();return /prepaid|prepayment|rent in advance|unexpired/.test(t)?'prepaid':/depreciation|useful life|salvage|long.lived/.test(t)?'equipment':/receivable|credit sale|on account|customer payment/.test(t)?'receivables':'capital';}
function day(a,d){return `${a.year}-${String(a.month).padStart(2,'0')}-${String(d).padStart(2,'0')}`;}
function end(a){return new Date(Date.UTC(a.year,a.month,0)).getUTCDate();}
function expected(a,choice){const opening=a.topic==='capital'?0:8000;let events=[],decision='',prediction={},effects=[];const event=(id,title,kind,date,amount,debit,credit,detail)=>events.push({id,title,kind,date,amount:cents(amount),debit,credit,detail});
if(a.topic==='prepaid'){const rate=[150,250,400][choice.location],months=choice.months;if(!rate||![1,3,6].includes(months))throw Error('Invalid rental choice');decision=`${['Quiet side street','Neighborhood main street','Town center'][choice.location]}, ${months} month${months===1?'':'s'} paid in advance`;event('payment','Commercial lease payment','lease',day(a,1),rate*months,'Prepaid Rent','Cash',{rate,months,location:choice.location});event('adjustment','Month-end rental coverage','coverage',day(a,end(a)),rate,'Rent Expense','Prepaid Rent',{rate,months});prediction={prompt:'At month-end, how much of the payment has the business used?',options:['One month of coverage','All of the prepaid coverage','None of the coverage'],correct:0,feedback:'One month of time has passed. The unused coverage remains an asset, regardless of how many months were paid for.'};effects=[{key:'expense',label:'Rent expense for the month',value:rate},{key:'remaining',label:'Prepaid rent remaining',value:rate*(months-1)},{key:'cash',label:'Ending cash',value:opening-rate*months}];}
if(a.topic==='receivables'){const sale=[400,700,1000][choice.order],paid=cents(sale*[.25,.5,1][choice.collection]);if(!sale||![0,1,2].includes(choice.collection))throw Error('Invalid customer choice');decision=`${['Small','Medium','Large'][choice.order]} customer order; ${[25,50,100][choice.collection]}% collected this month`;event('sale','Customer order completed','invoice',day(a,8),sale,'Accounts Receivable','Sales Revenue',{sale});event('collection','Customer payment received','remittance',day(a,22),paid,'Cash','Accounts Receivable',{sale,paid});prediction={prompt:'What happens to revenue when this customer pays an existing invoice?',options:['Revenue increases again','Revenue stays the same','Revenue decreases'],correct:1,feedback:'Revenue was earned when services were delivered. The later payment changes Cash and Accounts Receivable, without earning the revenue again.'};effects=[{key:'revenue',label:'Revenue earned this month',value:sale},{key:'remaining',label:'Customer balance remaining',value:sale-paid},{key:'cash',label:'Ending cash',value:opening+paid}];}
if(a.topic==='equipment'){const cost=[600,1200,1800][choice.level],life=[3,5,6][choice.life];if(!cost||!life)throw Error('Invalid equipment choice');const dep=cents(cost/life/12);decision=`${['Starter','Expanded','Professional'][choice.level]} equipment; ${life}-year useful-life estimate`;event('purchase','Equipment delivered and paid','equipment',day(a,1),cost,'Equipment','Cash',{cost,life});event('depreciation','Month-end asset register','asset',day(a,end(a)),dep,'Depreciation Expense','Accumulated Depreciation',{cost,life});prediction={prompt:'Does the month-end depreciation adjustment require a new cash payment?',options:['Yes, the full purchase price','Yes, the monthly depreciation amount','No new cash payment'],correct:2,feedback:'Cash was paid when the equipment was purchased. Depreciation allocates that recorded cost to periods of use; it is a noncash adjustment.'};effects=[{key:'expense',label:'Depreciation expense for one month',value:dep},{key:'remaining',label:'Net equipment value',value:cents(cost-dep)},{key:'cash',label:'Ending cash',value:opening-cost}];}
if(a.topic==='capital'){const investment=[3000,5000,7000][choice.investment],ad=[60,120,200][choice.ad];if(!investment||!ad)throw Error('Invalid funding choice');decision=`Owner contribution $${investment}; advertising package $${ad}`;event('investment','Owner funds deposited','deposit',day(a,1),investment,'Cash','Owner Capital',{investment});event('advertising','Advertising campaign delivered','advertising',day(a,10),ad,'Advertising Expense','Cash',{ad});prediction={prompt:'Does money contributed by the owner count as sales revenue?',options:['Yes, any cash received is revenue','No, it increases owner equity','Only if the business spends it'],correct:1,feedback:'The owner supplied capital rather than purchasing a service from the business. Cash and owner equity increase; revenue does not.'};effects=[{key:'capital',label:'Owner capital contributed',value:investment},{key:'expense',label:'Advertising expense',value:ad},{key:'cash',label:'Ending cash',value:investment-ad}];}
return {opening,events,decision,prediction,effects};}
function validateRows(rows){if(rows.length<2||rows.length>8)return 'Use between two and eight lines.';let d=0,c=0;for(const r of rows){if(!accounts.includes(r.account))return 'Choose an account for every line.';const debit=Number(r.debit||0),credit=Number(r.credit||0);if(!Number.isFinite(debit)||!Number.isFinite(credit)||debit<0||credit<0||(debit>0)===(credit>0))return 'Each line needs a positive debit or a positive credit.';d+=Math.round(debit*100);c+=Math.round(credit*100);}return d===c?null:'Debits and credits do not balance.';}
function assess(rows,date,e){const b={};for(const r of rows)b[r.account]=(b[r.account]||0)+Math.round((Number(r.debit||0)-Number(r.credit||0))*100);const used=Object.keys(b).filter(a=>b[a]!==0);const account=used.length===2&&used.includes(e.debit)&&used.includes(e.credit);const amount=account&&b[e.debit]===Math.round(e.amount*100)&&b[e.credit]===-Math.round(e.amount*100);return {account,amount,date:date===e.date,correct:account&&amount&&date===e.date};}
function balances(scenario,entries){const b=Object.fromEntries(accounts.map(a=>[a,0]));b.Cash=scenario.opening;b['Owner Capital']=-scenario.opening;for(const e of Object.values(entries))for(const r of e.rows)b[r.account]+=Math.round((Number(r.debit||0)-Number(r.credit||0))*100)/100;return Object.fromEntries(Object.entries(b).map(([a,v])=>[a,cents(v)]));}
function grade(run){let journal=0;for(const e of run.scenario.events){const f=run.first[e.id];if(f)journal+=(f.account?1:0)+(f.amount?1:0)+(f.date?1:0);}return {journal:Math.round(80*journal/(run.scenario.events.length*3)),prediction:run.predictionFirst===run.scenario.prediction.correct?5:0,effects:run.effectsFirst?Math.round(15*run.scenario.effects.filter(e=>Math.abs(Number(run.effectsFirst[e.key])-e.value)<.005).length/run.scenario.effects.length):0};}
const api={topics,accounts,checkAssignment,suggestTopic,expected,validateRows,assess,balances,grade,day,end};if(typeof module!=='undefined')module.exports=api;else root.Lessons=api;
})(globalThis);
